export const geofenceCategories = [
  {key:'atm',label:'ATM',icon:'Banknote',color:'#08a9a3'},
  {key:'airport',label:'Airport',icon:'Plane',color:'#3467d6'},
  {key:'bank',label:'Bank',icon:'Landmark',color:'#5267a5'},
  {key:'beach',label:'Beach',icon:'Umbrella',color:'#008bb5'},
  {key:'bus_stop',label:'Bus Stop',icon:'BusFront',color:'#d47b19'},
  {key:'restaurant',label:'Restaurant',icon:'Utensils',color:'#dc573f'},
  {key:'dairy',label:'Dairy',icon:'Milk',color:'#4386bc'},
  {key:'district',label:'District',icon:'Map',color:'#6d709c'},
  {key:'facility',label:'Facility',icon:'Building2',color:'#587b8d'},
  {key:'factory',label:'Factory',icon:'Factory',color:'#66727d'},
  {key:'fuel_station',label:'Fuel Station',icon:'Fuel',color:'#e06136'},
  {key:'highway_point',label:'Highway Point',icon:'Route',color:'#616b78'},
  {key:'home',label:'Home',icon:'House',color:'#4f8e5e'},
  {key:'hospital',label:'Hospital',icon:'Hospital',color:'#d34b57'},
  {key:'hotel',label:'Hotel',icon:'Hotel',color:'#8557b4'},
  {key:'mosque',label:'Mosque',icon:'MoonStar',color:'#15896f'},
  {key:'office',label:'Office',icon:'BriefcaseBusiness',color:'#4a6fa1'},
  {key:'other',label:'Other',icon:'MapPin',color:'#718096'},
  {key:'police_station',label:'Police Station',icon:'Shield',color:'#2855a6'},
  {key:'post_office',label:'Post Office',icon:'Mail',color:'#b15548'},
  {key:'railway_station',label:'Railway Station',icon:'TrainFront',color:'#585f68'},
  {key:'recycle_station',label:'Recycle Station',icon:'Recycle',color:'#31925a'},
  {key:'school',label:'School',icon:'School',color:'#c88722'},
  {key:'traffic_signal',label:'Traffic Signal',icon:'TrafficCone',color:'#e1563f'},
  {key:'state_border',label:'State Border',icon:'Fence',color:'#687381'},
  {key:'sub_division',label:'Sub Division',icon:'LandPlot',color:'#738f4d'},
  {key:'temple',label:'Temple',icon:'Landmark',color:'#dc7828'},
  {key:'theater',label:'Theater',icon:'Theater',color:'#9b4c9b'},
  {key:'theme_park',label:'Theme Park',icon:'FerrisWheel',color:'#cf4e85'},
  {key:'toll_gate',label:'Toll Gate',icon:'CircleDollarSign',color:'#517193'},
  {key:'tunnel',label:'Tunnel',icon:'TrainFrontTunnel',color:'#5f6873'},
  {key:'university',label:'University',icon:'University',color:'#7353a5'},
  {key:'way_bridge',label:'Way Bridge',icon:'Construction',color:'#b2742d'},
  {key:'sensitive_points',label:'Sensitive Points',icon:'ShieldAlert',color:'#c63d3d'},
  {key:'dumping_yard',label:'Dumping Yard',icon:'Trash2',color:'#68766e'},
  {key:'mine',label:'Mine',icon:'Mountain',color:'#745e4d'},
  {key:'no_poi_report',label:'No POI Report',icon:'Ban',color:'#7a7d82'},
  {key:'entry_restriction',label:'Entry Restriction',icon:'LogIn',color:'#bd4b45'},
  {key:'tyre_shop',label:'Tyre Shop',icon:'CircleDot',color:'#5b6470'},
  {key:'workshop',label:'Workshop',icon:'Wrench',color:'#9b642d'},
  {key:'yard',label:'Yard',icon:'Warehouse',color:'#5e7c8c'},
  {key:'parking_place',label:'Parking Place',icon:'CircleParking',color:'#3474b8'},
  {key:'driver_home',label:'Driver Home',icon:'MapPinHouse',color:'#4f8a63'},
  {key:'customer',label:'Customer',icon:'CircleUserRound',color:'#397da0'},
  {key:'pushpakom',label:'Pushpakom',icon:'Navigation',color:'#5568bd'},
  {key:'exit_restriction',label:'Exit Restriction',icon:'LogOut',color:'#bd4b45'},
  {key:'gurudwara',label:'Gurudwara',icon:'Landmark',color:'#d18629'},
  {key:'church',label:'Church',icon:'Church',color:'#7962a4'},
  {key:'distributor',label:'Distributor',icon:'Package',color:'#a36832'},
  {key:'state',label:'State',icon:'Map',color:'#516fa3'},
  {key:'waterfall',label:'Waterfall',icon:'Waves',color:'#168bb3'},
  {key:'depot',label:'Depot',icon:'Warehouse',color:'#607d8b'},
  {key:'terminal',label:'Terminal',icon:'Building',color:'#4f667a'},
  {key:'port',label:'Port',icon:'Ship',color:'#187da0'},
] as const;

export type GeofenceCategory = (typeof geofenceCategories)[number];
export type GeofenceCategoryIconKey = GeofenceCategory['icon'];
export type Coordinate = [number, number]; // GeoJSON: longitude, latitude.
export type FenceGeometry = {type:'Point';coordinates:Coordinate}|{type:'Polygon';coordinates:Coordinate[][]};
export type FenceShape = 'POINT'|'POLYGON'|'RECTANGLE'|'CIRCLE';
export interface GeofenceInput {name:string;categoryKey:string;shapeType:FenceShape;geometry:FenceGeometry;radiusMeters:number|null;vehicleIds:string[]}
export interface Geofence extends GeofenceInput {id:string;created_at:string;updated_at:string;vehicles:{id:string;vehicle_number:string}[]}
