import {Router,type Router as RouterType,type Response,type NextFunction} from 'express';
import {z} from 'zod';
import {authorize,type AuthRequest} from '../middleware/auth.js';
import * as alerts from '../modules/alerts/repository.js';
import {uploadAnnouncementImage} from '../modules/profile/cloudinary.js';
import {ALERT_EVENTS,alertEventTypes} from '../modules/alerts/registry.js';
const route=(fn:(req:AuthRequest,res:Response)=>Promise<unknown>)=>(req:AuthRequest,res:Response,next:NextFunction)=>{void fn(req,res).catch(next)};
const paging=z.object({search:z.string().trim().max(100).default(''),page:z.coerce.number().int().min(1).max(1000000).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25)});
const alertBody=z.object({name:z.string().trim().min(1).max(120),mappingType:z.enum(['ALL_VEHICLES','CLIENT','VEHICLE']),mappingValue:z.string().uuid().nullable().optional(),events:z.array(z.enum(alertEventTypes)).min(1).max(alertEventTypes.length).transform(values=>[...new Set(values)]),active:z.boolean().default(true)}).superRefine((value,context)=>{if(value.mappingType==='ALL_VEHICLES'&&value.mappingValue)context.addIssue({code:'custom',path:['mappingValue'],message:'All vehicles cannot have a mapping value'});if(value.mappingType!=='ALL_VEHICLES'&&!value.mappingValue)context.addIssue({code:'custom',path:['mappingValue'],message:'Select a mapping value'})});
const announcementBody=z.object({targetType:z.enum(['ADMIN','CLIENT']),adminIds:z.array(z.string().uuid()).max(100).default([]).transform(values=>[...new Set(values)]),clientIds:z.array(z.string().uuid()).max(100).default([]).transform(values=>[...new Set(values)]),messageType:z.enum(['TEXT','IMAGE']).default('TEXT'),title:z.string().trim().min(1).max(160),bodyHtml:z.string().max(20000).default(''),imageUrl:z.string().url().optional().nullable(),imagePublicId:z.string().optional().nullable(),startsAt:z.coerce.date(),endsAt:z.coerce.date(),active:z.boolean().default(true),dontShowAgain:z.boolean().default(false)}).superRefine((value,context)=>{if(value.messageType==='IMAGE'&&(!value.imageUrl||!value.imagePublicId))context.addIssue({code:'custom',path:['imageUrl'],message:'Image is required'});if(value.messageType==='TEXT'&&!value.bodyHtml.trim())context.addIssue({code:'custom',path:['bodyHtml'],message:'Message body is required'});if(value.endsAt<value.startsAt)context.addIssue({code:'custom',path:['endsAt'],message:'End date must be after start date'});if(value.targetType==='ADMIN'&&!value.adminIds.length)context.addIssue({code:'custom',path:['adminIds'],message:'Select at least one admin'});if(value.targetType==='ADMIN'&&value.clientIds.length)context.addIssue({code:'custom',path:['clientIds'],message:'Admin announcements cannot include clients'});if(value.targetType==='CLIENT'&&value.adminIds.length!==1)context.addIssue({code:'custom',path:['adminIds'],message:'Select one admin'});if(value.targetType==='CLIENT'&&!value.clientIds.length)context.addIssue({code:'custom',path:['clientIds'],message:'Select at least one client'})});

export const alertsApi:RouterType=Router();
alertsApi.get('/alerts/events',(_req,res)=>res.json({success:true,data:ALERT_EVENTS}));
alertsApi.get('/alerts/mapping-options',route(async(req,res)=>{const q=z.object({type:z.enum(['CLIENT','VEHICLE']),search:z.string().trim().max(100).default('')}).parse(req.query);res.json({success:true,data:(await alerts.mappingOptions(req.user!.id,q.type,q.search)).rows})}));
alertsApi.get('/alerts',route(async(req,res)=>{const q=paging.parse(req.query),result=await alerts.listAlerts(req.user!.id,q.search,q.page,q.pageSize);res.json({success:true,data:result.rows,pagination:{...q,total:result.total}})}));
alertsApi.get('/alerts/:id',route(async(req,res)=>res.json({success:true,data:await alerts.getAlert(req.user!.id,z.string().uuid().parse(req.params.id))})));
alertsApi.post('/alerts',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>res.status(201).json({success:true,data:await alerts.saveAlert(req.user!.id,alertBody.parse(req.body))})));
alertsApi.patch('/alerts/:id',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>res.json({success:true,data:await alerts.saveAlert(req.user!.id,alertBody.parse(req.body),z.string().uuid().parse(req.params.id))})));
alertsApi.patch('/alerts/:id/status',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>res.json({success:true,data:await alerts.setAlertStatus(req.user!.id,z.string().uuid().parse(req.params.id),z.object({active:z.boolean()}).parse(req.body).active)})));
alertsApi.delete('/alerts/:id',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>{await alerts.archiveAlert(req.user!.id,z.string().uuid().parse(req.params.id));res.status(204).end()}));

alertsApi.get('/notifications',route(async(req,res)=>{const q=paging.extend({eventType:z.enum(alertEventTypes).optional(),vehicleId:z.string().uuid().optional(),clientId:z.string().uuid().optional(),from:z.coerce.date().optional(),to:z.coerce.date().optional(),sort:z.enum(['asc','desc']).default('desc')}).parse(req.query);const result=await alerts.listAllNotifications(req.user!.id,q);res.json({success:true,data:result.rows,pagination:{page:q.page,pageSize:q.pageSize,total:result.total}})}));
alertsApi.get('/notifications/:id',route(async(req,res)=>res.json({success:true,data:await alerts.getAnyNotification(req.user!.id,z.string().uuid().parse(req.params.id))})));

alertsApi.post('/announcements/image',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>{const dataUri=z.string().max(7*1024*1024).parse(req.body?.dataUri);res.status(201).json({success:true,data:await uploadAnnouncementImage(req.user!.id,dataUri)})}));
alertsApi.delete('/announcements/image',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>{await alerts.discardAnnouncementImage(req.user!.id,z.string().min(1).parse(req.body?.publicId));res.status(204).end()}));
alertsApi.get('/announcements/current',route(async(req,res)=>res.json({success:true,data:(await alerts.activeAnnouncements(req.user!.id)).rows})));
alertsApi.get('/announcements',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>{const q=paging.parse(req.query),result=await alerts.listAnnouncements(req.user!.id,q.search,q.page,q.pageSize);res.json({success:true,data:result.rows,pagination:{...q,total:result.total}})}));
alertsApi.get('/announcements/target-options',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>{const q=z.object({type:z.enum(['ADMIN','CLIENT']),adminId:z.string().uuid().optional(),search:z.string().trim().max(100).default('')}).parse(req.query);res.json({success:true,data:(await alerts.announcementTargetOptions(req.user!.id,q.type,q.search,q.adminId)).rows})}));
alertsApi.get('/announcements/:id',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>res.json({success:true,data:await alerts.getAnnouncement(req.user!.id,z.string().uuid().parse(req.params.id))})));
alertsApi.post('/announcements',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>res.status(201).json({success:true,data:await alerts.saveAnnouncement(req.user!.id,announcementBody.parse(req.body))})));
alertsApi.patch('/announcements/:id',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>res.json({success:true,data:await alerts.saveAnnouncement(req.user!.id,announcementBody.parse(req.body),z.string().uuid().parse(req.params.id))})));
alertsApi.delete('/announcements/:id',authorize('SUPER_ADMIN','ADMIN'),route(async(req,res)=>{await alerts.archiveAnnouncement(req.user!.id,z.string().uuid().parse(req.params.id));res.status(204).end()}));
alertsApi.post('/announcements/:id/dismiss',route(async(req,res)=>{await alerts.dismissAnnouncement(req.user!.id,z.string().uuid().parse(req.params.id));res.status(204).end()}));
