import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {PGlite} from '@electric-sql/pglite';import {afterAll,beforeAll,describe,expect,it,vi} from 'vitest';import express from 'express';import request from 'supertest';import jwt from 'jsonwebtoken';
const state=vi.hoisted(()=>({db:undefined as PGlite|undefined}));
vi.mock('../db/pool.js',()=>({query:async(sql:string,values?:unknown[])=>{const result=await state.db!.query(sql,values);return{rows:result.rows,rowCount:result.affectedRows||result.rows.length}},transaction:async(work:(client:{query:(sql:string,values?:unknown[])=>Promise<unknown>})=>Promise<unknown>)=>work({query:async(sql:string,values?:unknown[])=>{const result=await state.db!.query(sql,values);return{rows:result.rows,rowCount:result.affectedRows||result.rows.length}}})}));
const secret='alerts-integration-secret-at-least-32-characters',admin=randomUUID(),other=randomUUID(),client=randomUUID(),vehicle=randomUUID(),otherVehicle=randomUUID();let app:express.Express;
beforeAll(async()=>{process.env.DATABASE_URL='postgresql://unused:unused@localhost/unused';process.env.JWT_SECRET=secret;process.env.JWT_REFRESH_SECRET=secret+'-refresh';process.env.INTERNAL_TRACKER_SECRET=secret+'-internal';process.env.CLOUDINARY_CLOUD_NAME='test';state.db=new PGlite();for(const name of ['001_initial.sql','002_current_device_state.sql','003_web_admin_foundation.sql','004_client_management.sql','005_vehicle_management.sql','014_packet_health_permission.sql','018_admin_permissions.sql']){let sql=await readFile(new URL(`../../../../database/migrations/${name}`,import.meta.url),'utf8');sql=sql.replace(/CREATE EXTENSION IF NOT EXISTS \w+;/g,'').replace(/geography\(Point, 4326\)/g,'point').replace(/CREATE INDEX locations_position_gist[^;]+;/g,'');await state.db.exec(sql)}await state.db.exec('CREATE TABLE geofences(id uuid PRIMARY KEY);');await state.db.exec(await readFile(new URL('../../../../database/migrations/007_alerts_and_announcements.sql',import.meta.url),'utf8'));await state.db.exec(await readFile(new URL('../../../../database/migrations/008_subscription_alerts.sql',import.meta.url),'utf8'));await state.db.exec(await readFile(new URL('../../../../database/migrations/010_announcement_recipients.sql',import.meta.url),'utf8'));await state.db.exec(await readFile(new URL('../../../../database/migrations/011_announcement_images.sql',import.meta.url),'utf8'));await state.db.query("INSERT INTO users(id,email,password_hash,role,name) VALUES($1,'admin@test.local','x','ADMIN','Admin'),($2,'other@test.local','x','ADMIN','Other'),($3,'client@test.local','x','CLIENT','Client')",[admin,other,client]);await state.db.query('UPDATE users SET owner_id=$1 WHERE id=$2',[admin,client]);await state.db.query("UPDATE users SET username=CASE WHEN id=$1 THEN 'admin.login' ELSE 'client.login' END WHERE id IN ($1,$2)",[admin,client]);await state.db.query("INSERT INTO vehicles(id,vehicle_number,owner_id) VALUES($1,'OWN-1',$2),($3,'OTHER-1',$4)",[vehicle,client,otherVehicle,other]);const {api}=await import('./api.js'),{errorHandler}=await import('../lib/errors.js');app=express();app.use(express.json());app.use('/api/v1',api);app.use(errorHandler)},30000);
afterAll(async()=>state.db?.close());const token=(id:string,role='ADMIN')=>jwt.sign({id,role},secret);const auth=(method:'get'|'post'|'patch'|'delete',path:string,id=admin)=>request(app)[method]('/api/v1'+path).set('Authorization',`Bearer ${token(id)}`);
describe('alert configuration API',()=>{let alertId:string;it('creates a scoped alert with multiple registry events',async()=>{const response=await auth('post','/alerts').send({name:'Operations',mappingType:'VEHICLE',mappingValue:vehicle,events:['VEHICLE_STOPPED','VEHICLE_OVERSPEED'],active:true}).expect(201);alertId=response.body.data.id;expect(response.body.data.events).toEqual(['VEHICLE_OVERSPEED','VEHICLE_STOPPED'])});it('rejects invalid events and out-of-scope mappings',async()=>{await auth('post','/alerts').send({name:'Bad',mappingType:'VEHICLE',mappingValue:vehicle,events:['FAKE'],active:true}).expect(400);await auth('post','/alerts',other).send({name:'IDOR',mappingType:'VEHICLE',mappingValue:vehicle,events:['VEHICLE_STOPPED'],active:true}).expect(403)});it('edits and deactivates without deleting history',async()=>{await auth('patch',`/alerts/${alertId}`).send({name:'Operations updated',mappingType:'ALL_VEHICLES',mappingValue:null,events:['VEHICLE_RUNNING'],active:true}).expect(200);const status=await auth('patch',`/alerts/${alertId}/status`).send({active:false}).expect(200);expect(status.body.data.active).toBe(false);await auth('get',`/alerts/${alertId}`,other).expect(404)})});
describe('notification authorization and filters',()=>{it('paginates and prevents cross-scope reads',async()=>{const alert=(await state.db!.query<{id:string}>('SELECT id FROM alert_configurations LIMIT 1')).rows[0].id;const notification=randomUUID(),foreignNotification=randomUUID();await state.db!.query("INSERT INTO notification_history(id,alert_id,vehicle_id,event_type,message,occurred_at,dedup_key) VALUES($1,$2,$3,'VEHICLE_RUNNING','Own running',now(),'own'),($4,NULL,$5,'VEHICLE_STOPPED','Foreign stopped',now(),'foreign')",[notification,alert,vehicle,foreignNotification,otherVehicle]);const list=await auth('get','/notifications?page=1&pageSize=1&eventType=VEHICLE_RUNNING').expect(200);expect(list.body.data).toHaveLength(1);expect(list.body.pagination.total).toBe(1);await auth('get',`/notifications/${foreignNotification}`).expect(404)})});
describe('announcements',()=>{it('targets the selected clients and admins, sanitizes HTML, and persists dismissal',async()=>{const start=new Date(Date.now()-60000).toISOString(),end=new Date(Date.now()+60000).toISOString();await auth('post','/announcements').send({targetType:'CLIENT',adminIds:[admin],clientIds:[client],messageType:'TEXT',title:'Invalid',bodyHtml:'x',startsAt:end,endsAt:start,active:true,dontShowAgain:true}).expect(400);const adminOptions=await auth('get','/announcements/target-options?type=ADMIN').expect(200);expect(adminOptions.body.data).toEqual([expect.objectContaining({id:admin,label:'Admin'})]);const options=await auth('get',`/announcements/target-options?type=CLIENT&adminId=${admin}`).expect(200);expect(options.body.data).toEqual([expect.objectContaining({id:client,label:'Client'})]);const created=await auth('post','/announcements').send({targetType:'CLIENT',adminIds:[admin],clientIds:[client],messageType:'TEXT',title:'Notice',bodyHtml:'<p>Hello<script>alert(1)</script></p>',startsAt:start,endsAt:end,active:true,dontShowAgain:true}).expect(201);expect(created.body.data).toMatchObject({targetType:'CLIENT',clients:['Client'],admins:['Admin']});expect(created.body.data.bodyHtml).not.toContain('<script>');const current=(id:string,role:string)=>request(app).get('/api/v1/announcements/current').set('Authorization',`Bearer ${jwt.sign({id,role},secret)}`);expect((await current(client,'CLIENT').expect(200)).body.data).toHaveLength(1);expect((await current(admin,'ADMIN').expect(200)).body.data).toHaveLength(0);const adminAnnouncement=await auth('post','/announcements').send({targetType:'ADMIN',adminIds:[admin],clientIds:[],messageType:'TEXT',title:'Admin Notice',bodyHtml:'<p>Admin only</p>',startsAt:start,endsAt:end,active:true,dontShowAgain:false}).expect(201);expect((await current(admin,'ADMIN').expect(200)).body.data.map((row:{id:string})=>row.id)).toEqual([adminAnnouncement.body.data.id]);expect((await current(client,'CLIENT').expect(200)).body.data.map((row:{id:string})=>row.id)).toEqual([created.body.data.id]);await request(app).post(`/api/v1/announcements/${created.body.data.id}/dismiss`).set('Authorization',`Bearer ${jwt.sign({id:client,role:'CLIENT'},secret)}`).expect(204);expect((await current(client,'CLIENT').expect(200)).body.data).toHaveLength(0);await auth('get',`/announcements/${created.body.data.id}`,other).expect(404)})});

describe('image announcements',()=>{
 it('validates content, persists images, and allows replacement and text conversion',async()=>{
  const startsAt=new Date(Date.now()-60000).toISOString(),endsAt=new Date(Date.now()+60000).toISOString();
  const base={targetType:'ADMIN',adminIds:[admin],clientIds:[],title:'Image notice',startsAt,endsAt,active:true,dontShowAgain:false};
  await auth('post','/announcements').send({...base,messageType:'IMAGE',bodyHtml:''}).expect(400);
  await auth('post','/announcements').send({...base,messageType:'VIDEO',bodyHtml:'x'}).expect(400);
  const imageUrl='https://res.cloudinary.com/test/image/upload/v1/example.png',imagePublicId=`fleet/announcements/${admin}/first`;
  const created=await auth('post','/announcements').send({...base,messageType:'IMAGE',bodyHtml:'',imageUrl,imagePublicId}).expect(201);
  expect(created.body.data).toMatchObject({messageType:'IMAGE',bodyHtml:null,imageUrl,imagePublicId});
  const nextId=`fleet/announcements/${admin}/second`;
  const replaced=await auth('patch',`/announcements/${created.body.data.id}`).send({...base,messageType:'IMAGE',bodyHtml:'',imageUrl,imagePublicId:nextId}).expect(200);
  expect(replaced.body.data.imagePublicId).toBe(nextId);
  const text=await auth('patch',`/announcements/${created.body.data.id}`).send({...base,messageType:'TEXT',bodyHtml:'<p>Back to text</p>',imageUrl:null,imagePublicId:null}).expect(200);
  expect(text.body.data).toMatchObject({messageType:'TEXT',imageUrl:null,imagePublicId:null});
 });
});