import type {PoolClient} from 'pg';
import {env} from '../../config/env.js';
import {query,transaction} from '../../db/pool.js';
import type {AlertEventType} from './registry.js';

export interface TelemetryAlertInput{latitude?:number|null;longitude?:number|null;speed?:number|null;ac?:boolean|null;door?:boolean|null;serverReceivedAt?:Date|string;fleet_status?:string;address?:string|null}
export interface PersistedNotification{id:string;vehicleId:string;eventType:AlertEventType;message:string;occurredAt:Date;latitude:number|null;longitude:number|null;address:string|null}
export type Candidate={type:AlertEventType;active:boolean;message:string;metadata?:Record<string,unknown>;notifyOnInitial?:boolean};
export const shouldCreateNotification=(previous:boolean|undefined,next:boolean,notifyOnInitial=true)=>next&&previous!==next&&(previous!==undefined||notifyOnInitial);
export function telemetryCandidates(vehicle:{vehicleNumber:string;overspeedLimit:number|null;doorConfigured:boolean;capabilities:Record<string,string>|null},input:TelemetryAlertInput):Candidate[]{const speed=input.speed==null?null:Number(input.speed),status=String(input.fleet_status??'').toUpperCase(),name=vehicle.vehicleNumber;const candidates:Candidate[]=[{type:'VEHICLE_RUNNING',active:status==='RUNNING',message:`Vehicle ${name} is running.`},{type:'VEHICLE_IDLE',active:status==='IDLE',message:`Vehicle ${name} is idle.`},{type:'VEHICLE_STOPPED',active:status==='STOPPED',message:`Vehicle ${name} has stopped.`},{type:'VEHICLE_OVERSPEED',active:speed!==null&&vehicle.overspeedLimit!==null&&speed>vehicle.overspeedLimit,message:`Vehicle ${name} is overspeeding at ${speed??0} km/h.`,metadata:{speed,limit:vehicle.overspeedLimit}},{type:'VEHICLE_ONLINE',active:true,message:`Vehicle ${name} is online.`,notifyOnInitial:false},{type:'VEHICLE_UNREACHABLE',active:false,message:`Vehicle ${name} is unreachable.`}];if(input.ac!==null&&input.ac!==undefined&&vehicle.capabilities?.airCondition==='SUPPORTED')candidates.push({type:'AC_ON',active:input.ac,message:`Vehicle ${name} AC is on.`},{type:'AC_OFF',active:!input.ac,message:`Vehicle ${name} AC is off.`});if(input.door!==null&&input.door!==undefined&&(vehicle.doorConfigured||vehicle.capabilities?.door==='SUPPORTED'))candidates.push({type:'DOOR_OPENED',active:input.door,message:`Vehicle ${name} door opened.`},{type:'DOOR_CLOSED',active:!input.door,message:`Vehicle ${name} door closed.`});return candidates}

async function matchingAlerts(client:PoolClient,vehicleId:string,eventType:AlertEventType){return client.query<{id:string}>(`WITH RECURSIVE vehicle_owner AS (SELECT owner_id id FROM vehicles WHERE id=$1), owner_chain AS (SELECT id FROM vehicle_owner UNION ALL SELECT u.owner_id FROM users u JOIN owner_chain c ON u.id=c.id WHERE u.owner_id IS NOT NULL) SELECT DISTINCT a.id FROM alert_configurations a JOIN alert_configuration_events e ON e.alert_id=a.id WHERE a.active AND a.archived_at IS NULL AND e.event_type=$2 AND a.owner_id IN (SELECT id FROM owner_chain) AND (a.mapping_type='ALL_VEHICLES' OR (a.mapping_type='VEHICLE' AND a.mapping_value=$1) OR (a.mapping_type='CLIENT' AND a.mapping_value=(SELECT owner_id FROM vehicles WHERE id=$1)))`,[vehicleId,eventType])}
async function transition(client:PoolClient,vehicleId:string,candidate:Candidate,occurredAt:Date,location:{latitude:number|null;longitude:number|null;address:string|null}){
 const prior=await client.query<{active:boolean;transition_number:string}>('SELECT active,transition_number FROM alert_vehicle_event_state WHERE vehicle_id=$1 AND event_type=$2 FOR UPDATE',[vehicleId,candidate.type]);
 const previous=prior.rows[0],changed=!previous||previous.active!==candidate.active,number=changed?Number(previous?.transition_number??0)+1:Number(previous?.transition_number??0);
 await client.query(`INSERT INTO alert_vehicle_event_state(vehicle_id,event_type,active,value,transition_number,updated_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(vehicle_id,event_type) DO UPDATE SET active=EXCLUDED.active,value=EXCLUDED.value,transition_number=EXCLUDED.transition_number,updated_at=EXCLUDED.updated_at`,[vehicleId,candidate.type,candidate.active,JSON.stringify(candidate.metadata??{}),number,occurredAt]);
 if(!changed||!shouldCreateNotification(previous?.active,candidate.active,candidate.notifyOnInitial??true))return [];
 const configs=await matchingAlerts(client,vehicleId,candidate.type),notifications:PersistedNotification[]=[];
 for(const config of configs.rows){const inserted=await client.query<{id:string;occurred_at:Date}>(`INSERT INTO notification_history(alert_id,vehicle_id,event_type,message,latitude,longitude,address,occurred_at,metadata,dedup_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(dedup_key) DO NOTHING RETURNING id,occurred_at`,[config.id,vehicleId,candidate.type,candidate.message,location.latitude,location.longitude,location.address,occurredAt,JSON.stringify(candidate.metadata??{}),`${config.id}:${vehicleId}:${candidate.type}:${number}`]);if(inserted.rows[0])notifications.push({id:inserted.rows[0].id,vehicleId,eventType:candidate.type,message:candidate.message,occurredAt:inserted.rows[0].occurred_at,latitude:location.latitude,longitude:location.longitude,address:location.address})}
 return notifications;
}

export async function processVehicleTelemetry(vehicleId:string,input:TelemetryAlertInput){return transaction(async client=>{
 const vehicle=(await client.query<{vehicle_number:string;overspeed_limit:number|null;door_configured:boolean;capabilities:Record<string,string>|null}>(`SELECT v.vehicle_number,v.overspeed_limit,v.door_configured,d.capabilities FROM vehicles v LEFT JOIN vehicle_device_assignments a ON a.vehicle_id=v.id AND a.unassigned_at IS NULL LEFT JOIN devices d ON d.id=a.device_id WHERE v.id=$1 AND v.active FOR SHARE OF v`,[vehicleId])).rows[0];if(!vehicle)return[];
 const at=new Date(input.serverReceivedAt??Date.now()),name=vehicle.vehicle_number;
 const candidates=telemetryCandidates({vehicleNumber:name,overspeedLimit:vehicle.overspeed_limit===null?null:Number(vehicle.overspeed_limit),doorConfigured:vehicle.door_configured,capabilities:vehicle.capabilities},input);
 const location={latitude:input.latitude??null,longitude:input.longitude??null,address:input.address??null},notifications:PersistedNotification[]=[];
 for(const candidate of candidates)notifications.push(...await transition(client,vehicleId,candidate,at,location));
 if(location.latitude!==null&&location.longitude!==null){const fences=await client.query<{id:string;name:string;inside:boolean}>(`SELECT g.id,g.name,CASE WHEN g.shape_type='CIRCLE' THEN ST_DWithin(g.geometry::geography,ST_SetSRID(ST_MakePoint($2,$1),4326)::geography,g.radius_meters) ELSE ST_Covers(g.geometry,ST_SetSRID(ST_MakePoint($2,$1),4326)) END inside FROM geofences g JOIN geofence_vehicle_assignments a ON a.geofence_id=g.id WHERE a.vehicle_id=$3 AND g.deleted_at IS NULL`,[location.latitude,location.longitude,vehicleId]);for(const fence of fences.rows){const previous=(await client.query<{inside:boolean}>('SELECT inside FROM alert_geofence_state WHERE geofence_id=$1 AND vehicle_id=$2 FOR UPDATE',[fence.id,vehicleId])).rows[0];await client.query('INSERT INTO alert_geofence_state(geofence_id,vehicle_id,inside,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT(geofence_id,vehicle_id) DO UPDATE SET inside=EXCLUDED.inside,updated_at=EXCLUDED.updated_at',[fence.id,vehicleId,fence.inside,at]);if(previous&&previous.inside!==fence.inside){const type:AlertEventType=fence.inside?'GEOFENCE_IN':'GEOFENCE_OUT';notifications.push(...await transition(client,vehicleId,{type,active:true,message:`Vehicle ${name} ${fence.inside?'entered':'left'} geofence ${fence.name}.`,metadata:{geofenceId:fence.id,geofenceName:fence.name}},at,location));await transition(client,vehicleId,{type,active:false,message:'',metadata:{geofenceId:fence.id}},new Date(at.getTime()+1),location)}}}
 return notifications;
 })}

export async function processUnreachableVehicles(){const stale=await query<{id:string;vehicle_number:string;latitude:number|null;longitude:number|null;address:string|null}>(`SELECT v.id,v.vehicle_number,l.latitude,l.longitude,NULLIF(l.metadata->>'address','') address FROM vehicles v JOIN vehicle_device_assignments a ON a.vehicle_id=v.id AND a.unassigned_at IS NULL JOIN devices d ON d.id=a.device_id LEFT JOIN LATERAL(SELECT latitude,longitude,metadata FROM locations WHERE vehicle_id=v.id ORDER BY server_received_at DESC LIMIT 1) l ON true WHERE v.active AND (d.last_seen_at IS NULL OR d.last_seen_at<now()-($1::int*interval '1 minute'))`,[env.NO_SIGNAL_TIMEOUT_MINUTES]);const all:PersistedNotification[]=[];for(const vehicle of stale.rows){all.push(...await transaction(async client=>{const location={latitude:vehicle.latitude,longitude:vehicle.longitude,address:vehicle.address};const out=await transition(client,vehicle.id,{type:'VEHICLE_UNREACHABLE',active:true,message:`Vehicle ${vehicle.vehicle_number} is unreachable.`},new Date(),location);await transition(client,vehicle.id,{type:'VEHICLE_ONLINE',active:false,message:''},new Date(),location);return out}))}return all}
