import type {PoolClient} from 'pg';
import {query,transaction} from '../../db/pool.js';
import {AppError} from '../../lib/errors.js';
import {userScopeCte} from '../authorization/scope.js';
import type {AlertEventType} from './registry.js';
import {sanitizeAnnouncementHtml,htmlText} from './sanitize.js';
import {deleteAnnouncementImage} from '../profile/cloudinary.js';
import {env} from '../../config/env.js';

export interface AlertInput{name:string;mappingType:'ALL_VEHICLES'|'CLIENT'|'VEHICLE';mappingValue?:string|null;events:AlertEventType[];active:boolean}
export interface AnnouncementInput{targetType:'ADMIN'|'CLIENT';adminIds:string[];clientIds:string[];messageType:'TEXT'|'IMAGE';title:string;bodyHtml:string;imageUrl?:string|null;imagePublicId?:string|null;startsAt:Date;endsAt:Date;active:boolean;dontShowAgain:boolean}
const alertFields=`a.id,a.name,a.mapping_type AS "mappingType",a.mapping_value AS "mappingValue",a.active,a.created_at AS "createdAt",a.updated_at AS "updatedAt",creator.email AS "createdBy",COALESCE(array_agg(e.event_type ORDER BY e.event_type) FILTER(WHERE e.event_type IS NOT NULL),'{}') AS events,
 CASE WHEN a.mapping_type='ALL_VEHICLES' THEN 'All vehicles' WHEN a.mapping_type='CLIENT' THEN COALESCE(target.name,target.email,'Unavailable') ELSE COALESCE(vehicle.vehicle_number,'Unavailable') END AS "mappingLabel"`;
export async function listAlerts(actor:string,search:string,page:number,pageSize:number){const result=await query(`${userScopeCte}, rows AS (SELECT ${alertFields},count(*) OVER()::int total FROM alert_configurations a JOIN user_scope s ON s.id=a.owner_id JOIN users creator ON creator.id=a.created_by LEFT JOIN alert_configuration_events e ON e.alert_id=a.id LEFT JOIN users target ON a.mapping_type='CLIENT' AND target.id=a.mapping_value LEFT JOIN vehicles vehicle ON a.mapping_type='VEHICLE' AND vehicle.id=a.mapping_value WHERE a.archived_at IS NULL AND ($2='%%' OR a.name ILIKE $2 OR COALESCE(target.name,target.email,vehicle.vehicle_number,'') ILIKE $2) GROUP BY a.id,creator.email,target.name,target.email,vehicle.vehicle_number ORDER BY a.updated_at DESC,a.id LIMIT $3 OFFSET $4) SELECT * FROM rows`,[actor,`%${search}%`,pageSize,(page-1)*pageSize]);return{rows:result.rows,total:Number(result.rows[0]?.total??0)}}
export async function getAlert(actor:string,id:string){const r=await query(`${userScopeCte} SELECT ${alertFields} FROM alert_configurations a JOIN user_scope s ON s.id=a.owner_id JOIN users creator ON creator.id=a.created_by LEFT JOIN alert_configuration_events e ON e.alert_id=a.id LEFT JOIN users target ON a.mapping_type='CLIENT' AND target.id=a.mapping_value LEFT JOIN vehicles vehicle ON a.mapping_type='VEHICLE' AND vehicle.id=a.mapping_value WHERE a.id=$2 AND a.archived_at IS NULL GROUP BY a.id,creator.email,target.name,target.email,vehicle.vehicle_number`,[actor,id]);if(!r.rows[0])throw new AppError(404,'ALERT_NOT_FOUND','Alert configuration not found');return r.rows[0]}
async function validateMapping(client:PoolClient,actor:string,input:AlertInput){if(input.mappingType==='ALL_VEHICLES')return;if(!input.mappingValue)throw new AppError(400,'MAPPING_REQUIRED','Select a mapping value');const sql=input.mappingType==='CLIENT'?`${userScopeCte} SELECT u.id FROM users u JOIN user_scope s ON s.id=u.id WHERE u.id=$2 AND u.role='CLIENT'`:`${userScopeCte} SELECT v.id FROM vehicles v JOIN user_scope s ON s.id=v.owner_id WHERE v.id=$2`;if(!(await client.query(sql,[actor,input.mappingValue])).rowCount)throw new AppError(403,'MAPPING_FORBIDDEN','The selected mapping is outside your scope')}
export async function saveAlert(actor:string,input:AlertInput,id?:string){const key=await transaction(async client=>{await validateMapping(client,actor,input);if(id&&!(await client.query(`${userScopeCte} SELECT a.id FROM alert_configurations a JOIN user_scope s ON s.id=a.owner_id WHERE a.id=$2 AND a.archived_at IS NULL FOR UPDATE OF a`,[actor,id])).rowCount)throw new AppError(404,'ALERT_NOT_FOUND','Alert configuration not found');let result;try{result=id?await client.query('UPDATE alert_configurations SET name=$1,mapping_type=$2,mapping_value=$3,active=$4,updated_at=now() WHERE id=$5 RETURNING id',[input.name,input.mappingType,input.mappingValue??null,input.active,id]):await client.query('INSERT INTO alert_configurations(owner_id,name,mapping_type,mapping_value,active,created_by) VALUES($1,$2,$3,$4,$5,$1) RETURNING id',[actor,input.name,input.mappingType,input.mappingValue??null,input.active])}catch(error){if((error as {code?:string}).code==='23505')throw new AppError(409,'ALERT_NAME_EXISTS','An alert with this name already exists');throw error}const alertId=result.rows[0].id as string;await client.query('DELETE FROM alert_configuration_events WHERE alert_id=$1',[alertId]);await client.query('INSERT INTO alert_configuration_events(alert_id,event_type) SELECT $1,unnest($2::text[])',[alertId,input.events]);return alertId});return getAlert(actor,key)}
export async function setAlertStatus(actor:string,id:string,active:boolean){const r=await query(`${userScopeCte} UPDATE alert_configurations a SET active=$3,updated_at=now() FROM user_scope s WHERE a.owner_id=s.id AND a.id=$2 AND a.archived_at IS NULL RETURNING a.id`,[actor,id,active]);if(!r.rowCount)throw new AppError(404,'ALERT_NOT_FOUND','Alert configuration not found');return getAlert(actor,id)}
export async function archiveAlert(actor:string,id:string){const r=await query(`${userScopeCte} UPDATE alert_configurations a SET active=false,archived_at=now(),updated_at=now() FROM user_scope s WHERE a.owner_id=s.id AND a.id=$2 AND a.archived_at IS NULL`,[actor,id]);if(!r.rowCount)throw new AppError(404,'ALERT_NOT_FOUND','Alert configuration not found')}
export async function mappingOptions(actor:string,type:'CLIENT'|'VEHICLE',search:string){return query(type==='CLIENT'?`${userScopeCte} SELECT u.id,COALESCE(u.name,u.email) AS label FROM users u JOIN user_scope s ON s.id=u.id WHERE u.role='CLIENT' AND (COALESCE(u.name,'') ILIKE $2 OR u.email ILIKE $2) ORDER BY label LIMIT 100`:`${userScopeCte} SELECT v.id,v.vehicle_number AS label FROM vehicles v JOIN user_scope s ON s.id=v.owner_id WHERE v.active AND v.vehicle_number ILIKE $2 ORDER BY label LIMIT 100`,[actor,`%${search}%`])}

export async function listNotifications(actor:string,filters:{search:string;page:number;pageSize:number;eventType?:string;vehicleId?:string;clientId?:string;from?:Date;to?:Date;sort:'asc'|'desc'}){const values:unknown[]=[actor,`%${filters.search}%`,filters.eventType??null,filters.vehicleId??null,filters.clientId??null,filters.from??null,filters.to??null,filters.pageSize,(filters.page-1)*filters.pageSize];const r=await query(`${userScopeCte} SELECT n.id,n.event_type AS "eventType",n.message,n.latitude,n.longitude,n.address,n.occurred_at AS "occurredAt",n.metadata,v.id AS "vehicleId",v.vehicle_number AS vehicle,owner.id AS "clientId",COALESCE(owner.name,owner.email) AS client,count(*) OVER()::int total FROM notification_history n JOIN vehicles v ON v.id=n.vehicle_id JOIN user_scope s ON s.id=v.owner_id JOIN users owner ON owner.id=v.owner_id WHERE ($2='%%' OR n.message ILIKE $2 OR v.vehicle_number ILIKE $2 OR COALESCE(n.address,'') ILIKE $2) AND ($3::text IS NULL OR n.event_type=$3) AND ($4::uuid IS NULL OR v.id=$4) AND ($5::uuid IS NULL OR v.owner_id=$5) AND ($6::timestamptz IS NULL OR n.occurred_at>=$6) AND ($7::timestamptz IS NULL OR n.occurred_at<=$7) ORDER BY n.occurred_at ${filters.sort==='asc'?'ASC':'DESC'},n.id ${filters.sort==='asc'?'ASC':'DESC'} LIMIT $8 OFFSET $9`,values);return{rows:r.rows,total:Number(r.rows[0]?.total??0)}}
export async function getNotification(actor:string,id:string){const r=await query(`${userScopeCte} SELECT n.id,n.event_type AS "eventType",n.message,n.latitude,n.longitude,n.address,n.occurred_at AS "occurredAt",n.metadata,v.id AS "vehicleId",v.vehicle_number AS vehicle FROM notification_history n JOIN vehicles v ON v.id=n.vehicle_id JOIN user_scope s ON s.id=v.owner_id WHERE n.id=$2`,[actor,id]);if(!r.rows[0])throw new AppError(404,'NOTIFICATION_NOT_FOUND','Notification not found');return r.rows[0]}
export async function listAllNotifications(actor:string,filters:{search:string;page:number;pageSize:number;eventType?:string;vehicleId?:string;clientId?:string;from?:Date;to?:Date;sort:'asc'|'desc'}){const values:unknown[]=[actor,`%${filters.search}%`,filters.eventType??null,filters.vehicleId??null,filters.clientId??null,filters.from??null,filters.to??null,filters.pageSize,(filters.page-1)*filters.pageSize];const direction=filters.sort==='asc'?'ASC':'DESC';const r=await query(`${userScopeCte} SELECT n.id,n.event_type AS "eventType",n.message,n.latitude,n.longitude,n.address,n.occurred_at AS "occurredAt",n.metadata,v.id AS "vehicleId",COALESCE(v.vehicle_number,'Unavailable') AS vehicle,owner.id AS "clientId",COALESCE(owner.name,owner.email,'Unavailable') AS client,count(*) OVER()::int total FROM notification_history n LEFT JOIN vehicles v ON v.id=n.vehicle_id LEFT JOIN users owner ON owner.id=COALESCE(v.owner_id,n.recipient_user_id) WHERE COALESCE(v.owner_id,n.recipient_user_id) IN (SELECT id FROM user_scope) AND ($2='%%' OR n.message ILIKE $2 OR COALESCE(v.vehicle_number,'') ILIKE $2 OR COALESCE(n.address,'') ILIKE $2) AND ($3::text IS NULL OR n.event_type=$3) AND ($4::uuid IS NULL OR v.id=$4) AND ($5::uuid IS NULL OR COALESCE(v.owner_id,n.recipient_user_id)=$5) AND ($6::timestamptz IS NULL OR n.occurred_at>=$6) AND ($7::timestamptz IS NULL OR n.occurred_at<=$7) ORDER BY n.occurred_at ${direction},n.id ${direction} LIMIT $8 OFFSET $9`,values);return{rows:r.rows,total:Number(r.rows[0]?.total??0)}}
export async function getAnyNotification(actor:string,id:string){const r=await query(`${userScopeCte} SELECT n.id,n.event_type AS "eventType",n.message,n.latitude,n.longitude,n.address,n.occurred_at AS "occurredAt",n.metadata,v.id AS "vehicleId",COALESCE(v.vehicle_number,'Unavailable') AS vehicle FROM notification_history n LEFT JOIN vehicles v ON v.id=n.vehicle_id WHERE n.id=$2 AND COALESCE(v.owner_id,n.recipient_user_id) IN (SELECT id FROM user_scope)`,[actor,id]);if(!r.rows[0])throw new AppError(404,'NOTIFICATION_NOT_FOUND','Notification not found');return r.rows[0]}

const announcementFields=`a.id,a.target_type AS "targetType",a.message_type AS "messageType",a.title,a.body_html AS "bodyHtml",a.image_url AS "imageUrl",a.image_public_id AS "imagePublicId",a.starts_at AS "startsAt",a.ends_at AS "endsAt",a.active,a.dont_show_again AS "dontShowAgain",a.created_at AS "createdAt",a.updated_at AS "updatedAt",COALESCE(NULLIF(TRIM(creator.name),''),creator.username,creator.email) AS "createdBy",
 CASE WHEN a.target_type='ADMIN' THEN 'Admin' WHEN a.target_type='CLIENT' THEN 'Client' ELSE 'All clients' END AS "targetLabel",
 COALESCE(ARRAY(SELECT label FROM (SELECT COALESCE(NULLIF(TRIM(recipient.name),''),recipient.username,recipient.email) label FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id WHERE ar.announcement_id=a.id AND recipient.role IN ('ADMIN','SUPER_ADMIN') UNION SELECT COALESCE(NULLIF(TRIM(owner.name),''),owner.username,owner.email) label FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id JOIN users owner ON owner.id=recipient.owner_id WHERE ar.announcement_id=a.id AND recipient.role='CLIENT') admin_labels ORDER BY label),'{}') AS admins,
 COALESCE(ARRAY(SELECT COALESCE(NULLIF(TRIM(recipient.name),''),recipient.username,recipient.email) FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id WHERE ar.announcement_id=a.id AND recipient.role='CLIENT' ORDER BY 1),'{}') AS clients,
 COALESCE(ARRAY(SELECT admin_id FROM (SELECT ar.user_id admin_id FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id WHERE ar.announcement_id=a.id AND recipient.role IN ('ADMIN','SUPER_ADMIN') UNION SELECT recipient.owner_id admin_id FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id WHERE ar.announcement_id=a.id AND recipient.role='CLIENT') admin_ids ORDER BY admin_id),'{}') AS "adminIds",
 COALESCE(ARRAY(SELECT ar.user_id FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id WHERE ar.announcement_id=a.id AND recipient.role='CLIENT' ORDER BY ar.user_id),'{}') AS "clientIds",
 (SELECT recipient.owner_id FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id WHERE ar.announcement_id=a.id AND recipient.role='CLIENT' ORDER BY recipient.id LIMIT 1) AS "selectedAdminId"`;
export async function listAnnouncements(actor:string,search:string,page:number,pageSize:number){const r=await query(`${userScopeCte} SELECT ${announcementFields},count(*) OVER()::int total FROM announcements a JOIN user_scope s ON s.id=a.owner_id JOIN users creator ON creator.id=a.created_by WHERE a.archived_at IS NULL AND ($2='%%' OR a.title ILIKE $2 OR a.body_html ILIKE $2 OR EXISTS(SELECT 1 FROM announcement_recipients ar JOIN users recipient ON recipient.id=ar.user_id WHERE ar.announcement_id=a.id AND COALESCE(NULLIF(TRIM(recipient.name),''),recipient.username,recipient.email) ILIKE $2)) ORDER BY a.updated_at DESC,a.id LIMIT $3 OFFSET $4`,[actor,`%${search}%`,pageSize,(page-1)*pageSize]);return{rows:r.rows,total:Number(r.rows[0]?.total??0)}}
export async function getAnnouncement(actor:string,id:string){const r=await query(`${userScopeCte} SELECT ${announcementFields} FROM announcements a JOIN user_scope s ON s.id=a.owner_id JOIN users creator ON creator.id=a.created_by WHERE a.id=$2 AND a.archived_at IS NULL`,[actor,id]);if(!r.rows[0])throw new AppError(404,'ANNOUNCEMENT_NOT_FOUND','Announcement not found');return r.rows[0]}
export async function announcementTargetOptions(actor:string,type:'ADMIN'|'CLIENT',search:string,adminId?:string){if(type==='CLIENT'&&!adminId)return{rows:[]};return query(`${userScopeCte} SELECT u.id,COALESCE(NULLIF(TRIM(u.name),''),u.username,u.email) label FROM users u JOIN user_scope s ON s.id=u.id WHERE u.active AND u.role=$2 AND ($3::uuid IS NULL OR u.owner_id=$3) AND (COALESCE(u.username,'') ILIKE $4 OR COALESCE(u.name,'') ILIKE $4 OR u.email ILIKE $4) ORDER BY label,u.id LIMIT 100`,[actor,type,adminId??null,`%${search}%`])}
async function validateTarget(client:PoolClient,actor:string,input:AnnouncementInput){const recipients=input.targetType==='ADMIN'?input.adminIds:input.clientIds,role=input.targetType;if(!recipients.length)throw new AppError(400,'TARGET_REQUIRED',`Select at least one ${role.toLowerCase()}`);const adminId=input.targetType==='CLIENT'?input.adminIds[0]:null;const visible=await client.query<{id:string}>(`${userScopeCte} SELECT u.id FROM users u JOIN user_scope s ON s.id=u.id WHERE u.id=ANY($2::uuid[]) AND u.role=$3 AND ($4::uuid IS NULL OR u.owner_id=$4)`,[actor,recipients,role,adminId]);if(visible.rowCount!==recipients.length)throw new AppError(403,'TARGET_FORBIDDEN','One or more selected recipients are outside your scope')}
export async function saveAnnouncement(actor:string,input:AnnouncementInput,id?:string){
 const body=input.messageType==='TEXT'?sanitizeAnnouncementHtml(input.bodyHtml):null;
 if(input.messageType==='TEXT'&&!htmlText(body??''))throw new AppError(400,'BODY_REQUIRED','Message body is required');
 if(input.messageType==='IMAGE'){
  const cloud=env.CLOUDINARY_CLOUD_NAME;
  if(!cloud||!input.imageUrl?.startsWith(`https://res.cloudinary.com/${cloud}/image/upload/`)||!input.imagePublicId?.startsWith('fleet/announcements/'))throw new AppError(400,'INVALID_ANNOUNCEMENT_IMAGE','Upload an announcement image first');
 }
 const result=await transaction(async client=>{
  await validateTarget(client,actor,input);
  let oldPublicId:string|null=null;
  if(id){const existing=await client.query<{image_public_id:string|null}>(`${userScopeCte} SELECT a.image_public_id FROM announcements a JOIN user_scope s ON s.id=a.owner_id WHERE a.id=$2 AND a.archived_at IS NULL FOR UPDATE OF a`,[actor,id]);if(!existing.rowCount)throw new AppError(404,'ANNOUNCEMENT_NOT_FOUND','Announcement not found');oldPublicId=existing.rows[0].image_public_id}
  const values=[input.targetType,input.messageType,input.title,body,input.startsAt,input.endsAt,input.active,input.dontShowAgain,input.messageType==='IMAGE'?input.imageUrl:null,input.messageType==='IMAGE'?input.imagePublicId:null];
  const r=id?await client.query('UPDATE announcements SET target_type=$1,target_id=NULL,message_type=$2,title=$3,body_html=$4,starts_at=$5,ends_at=$6,active=$7,dont_show_again=$8,image_url=$9,image_public_id=$10,updated_at=now() WHERE id=$11 RETURNING id',[...values,id]):await client.query('INSERT INTO announcements(owner_id,target_type,target_id,message_type,title,body_html,starts_at,ends_at,active,dont_show_again,image_url,image_public_id,created_by) VALUES($11,$1,NULL,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id',[...values,actor]);
  const announcementId=r.rows[0].id as string,recipients=input.targetType==='ADMIN'?input.adminIds:input.clientIds;
  await client.query('DELETE FROM announcement_recipients WHERE announcement_id=$1',[announcementId]);
  await client.query('INSERT INTO announcement_recipients(announcement_id,user_id) SELECT $1,unnest($2::uuid[])',[announcementId,recipients]);
  return {announcementId,oldPublicId};
 });
 if(result.oldPublicId&&result.oldPublicId!==input.imagePublicId)void deleteAnnouncementImage(result.oldPublicId).catch(()=>{});
 return getAnnouncement(actor,result.announcementId);
}
export async function archiveAnnouncement(actor:string,id:string){const r=await query<{image_public_id:string|null}>(`${userScopeCte} UPDATE announcements a SET active=false,archived_at=now(),updated_at=now() FROM user_scope s WHERE a.owner_id=s.id AND a.id=$2 AND a.archived_at IS NULL RETURNING a.image_public_id`,[actor,id]);if(!r.rowCount)throw new AppError(404,'ANNOUNCEMENT_NOT_FOUND','Announcement not found');if(r.rows[0].image_public_id)void deleteAnnouncementImage(r.rows[0].image_public_id).catch(()=>{})}
export async function discardAnnouncementImage(actor:string,publicId:string){
 if(!publicId.startsWith(`fleet/announcements/${actor}/`))throw new AppError(403,'IMAGE_FORBIDDEN','Image is outside your scope');
 const used=await query('SELECT 1 FROM announcements WHERE image_public_id=$1 AND archived_at IS NULL LIMIT 1',[publicId]);
 if(used.rowCount)throw new AppError(409,'IMAGE_IN_USE','Image is in use');
 void deleteAnnouncementImage(publicId).catch(()=>{});
}
export async function activeAnnouncements(actor:string){return query(`WITH RECURSIVE principal_chain AS (SELECT id,owner_id,role FROM users WHERE id=$1 UNION ALL SELECT u.id,u.owner_id,u.role FROM users u JOIN principal_chain p ON u.id=p.owner_id) SELECT ${announcementFields} FROM announcements a JOIN users creator ON creator.id=a.created_by WHERE a.archived_at IS NULL AND a.active AND now() BETWEEN a.starts_at AND a.ends_at AND a.owner_id IN (SELECT id FROM principal_chain) AND ((a.target_type IN ('ADMIN','CLIENT') AND EXISTS(SELECT 1 FROM announcement_recipients ar WHERE ar.announcement_id=a.id AND ar.user_id=$1)) OR (a.target_type='ALL_CLIENTS' AND (SELECT role FROM principal_chain WHERE id=$1)='CLIENT')) AND (NOT a.dont_show_again OR NOT EXISTS(SELECT 1 FROM announcement_dismissals d WHERE d.announcement_id=a.id AND d.user_id=$1)) ORDER BY a.starts_at DESC`,[actor])}
export async function dismissAnnouncement(actor:string,id:string){const visible=await activeAnnouncements(actor);if(!visible.rows.some(row=>row.id===id))throw new AppError(404,'ANNOUNCEMENT_NOT_FOUND','Announcement not found');await query('INSERT INTO announcement_dismissals(announcement_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,actor])}

// Recipient reads never use the management/creator scope as a substitute for targeting.
const recipientAnnouncementsCte=`WITH RECURSIVE principal_chain AS (
 SELECT id,owner_id,role FROM users WHERE id=$1 AND active
 UNION SELECT u.id,u.owner_id,u.role FROM users u JOIN principal_chain p ON u.id=p.owner_id
), received AS (
 SELECT a.id,a.title,a.body_html AS "bodyHtml",a.message_type AS "messageType",a.image_url AS "imageUrl",
 a.starts_at AS "startsAt",a.ends_at AS "endsAt",a.created_at AS "createdAt",a.updated_at AS "updatedAt",
 a.dont_show_again AS "dontShowAgain",r.read_at AS "readAt",
 (r.read_at IS NULL OR r.read_at<a.updated_at) AND (d.dismissed_at IS NULL OR d.dismissed_at<a.updated_at) AS unread,
 d.dismissed_at IS NOT NULL AND d.dismissed_at>=a.updated_at AS dismissed
 FROM announcements a
 LEFT JOIN announcement_reads r ON r.announcement_id=a.id AND r.user_id=$1
 LEFT JOIN announcement_dismissals d ON d.announcement_id=a.id AND d.user_id=$1
 WHERE a.archived_at IS NULL AND a.active AND now() BETWEEN a.starts_at AND a.ends_at
 AND a.owner_id IN (SELECT id FROM principal_chain)
 AND (EXISTS(SELECT 1 FROM announcement_recipients ar WHERE ar.announcement_id=a.id AND ar.user_id=$1)
 OR (a.target_type='ALL_CLIENTS' AND (SELECT role FROM principal_chain WHERE id=$1)='CLIENT'))
)`;
export async function myAnnouncements(actor:string){
 const result=await query(`${recipientAnnouncementsCte} SELECT * FROM received ORDER BY "startsAt" DESC,id`,[actor]);
 return {rows:result.rows,unreadCount:result.rows.filter(row=>row.unread).length};
}
export async function readReceivedAnnouncement(actor:string,id:string){
 const result=await query(`${recipientAnnouncementsCte} INSERT INTO announcement_reads(announcement_id,user_id)
 SELECT id,$1 FROM received WHERE id=$2
 ON CONFLICT(announcement_id,user_id) DO UPDATE SET read_at=now() RETURNING announcement_id`,[actor,id]);
 if(!result.rowCount)throw new AppError(404,'ANNOUNCEMENT_NOT_FOUND','Announcement not found');
}
export async function dismissReceivedAnnouncement(actor:string,id:string){
 const result=await query(`${recipientAnnouncementsCte} INSERT INTO announcement_dismissals(announcement_id,user_id)
 SELECT id,$1 FROM received WHERE id=$2
 ON CONFLICT(announcement_id,user_id) DO UPDATE SET dismissed_at=now() RETURNING announcement_id`,[actor,id]);
 if(!result.rowCount)throw new AppError(404,'ANNOUNCEMENT_NOT_FOUND','Announcement not found');
}
