import type {PoolClient} from 'pg';
import {query,transaction} from '../../db/pool.js';
import type {AlertEventType} from './registry.js';

export interface SubscriptionNotification{id:string;vehicleId:null;recipientUserId:string;eventType:AlertEventType;message:string;occurredAt:Date;latitude:null;longitude:null;address:null}
export const subscriptionIsExpired=(status:string,endsAt:Date|null,now=new Date())=>status.toLowerCase()==='expired'||Boolean(endsAt&&endsAt.getTime()<=now.getTime());
async function matching(client:PoolClient,userId:string,eventType:AlertEventType){return client.query<{id:string}>(`WITH RECURSIVE owner_chain AS (SELECT id,owner_id FROM users WHERE id=$1 UNION ALL SELECT u.id,u.owner_id FROM users u JOIN owner_chain c ON u.id=c.owner_id) SELECT DISTINCT a.id FROM alert_configurations a JOIN alert_configuration_events e ON e.alert_id=a.id WHERE a.active AND a.archived_at IS NULL AND e.event_type=$2 AND a.owner_id IN (SELECT id FROM owner_chain) AND (a.mapping_type='ALL_VEHICLES' OR (a.mapping_type='CLIENT' AND a.mapping_value=$1))`,[userId,eventType])}
async function applyTransition(client:PoolClient,subscription:{id:string;user_id:string;label:string;status:string;ends_at:Date|null},eventType:AlertEventType,active:boolean,notifyOnInitial:boolean,message:string){const prior=await client.query<{active:boolean;transition_number:string}>('SELECT active,transition_number FROM alert_subscription_event_state WHERE subscription_id=$1 AND event_type=$2 FOR UPDATE',[subscription.id,eventType]),previous=prior.rows[0],changed=!previous||previous.active!==active,transitionNumber=changed?Number(previous?.transition_number??0)+1:Number(previous?.transition_number??0);await client.query(`INSERT INTO alert_subscription_event_state(subscription_id,event_type,active,value,transition_number,updated_at) VALUES($1,$2,$3,$4,$5,now()) ON CONFLICT(subscription_id,event_type) DO UPDATE SET active=EXCLUDED.active,value=EXCLUDED.value,transition_number=EXCLUDED.transition_number,updated_at=now()`,[subscription.id,eventType,active,JSON.stringify({status:subscription.status,endsAt:subscription.ends_at}),transitionNumber]);if(!changed||!active||(previous===undefined&&!notifyOnInitial))return[];const configs=await matching(client,subscription.user_id,eventType),result:SubscriptionNotification[]=[];for(const config of configs.rows){const inserted=await client.query<{id:string;occurred_at:Date}>(`INSERT INTO notification_history(alert_id,recipient_user_id,subscription_id,event_type,message,occurred_at,dedup_key,metadata) VALUES($1,$2,$3,$4,$5,now(),$6,$7) ON CONFLICT(dedup_key) DO NOTHING RETURNING id,occurred_at`,[config.id,subscription.user_id,subscription.id,eventType,message,`${config.id}:${subscription.id}:${eventType}:${transitionNumber}`,JSON.stringify({status:subscription.status,endsAt:subscription.ends_at})]);if(inserted.rows[0])result.push({id:inserted.rows[0].id,vehicleId:null,recipientUserId:subscription.user_id,eventType,message,occurredAt:inserted.rows[0].occurred_at,latitude:null,longitude:null,address:null})}return result}
export async function processSubscriptionAlerts(){const subscriptions=await query<{id:string;user_id:string;label:string;status:string;ends_at:Date|null}>(`SELECT s.id,s.user_id,COALESCE(u.name,u.email) label,s.status,s.ends_at FROM subscriptions s JOIN users u ON u.id=s.user_id`),notifications:SubscriptionNotification[]=[];for(const subscription of subscriptions.rows){notifications.push(...await transaction(async client=>{const expired=subscriptionIsExpired(subscription.status,subscription.ends_at),result:SubscriptionNotification[]=[];result.push(...await applyTransition(client,subscription,'SUBSCRIPTION_EXPIRED',expired,true,`Subscription for ${subscription.label} has expired.`));result.push(...await applyTransition(client,subscription,'SUBSCRIPTION_RENEWED',!expired,false,`Subscription for ${subscription.label} has renewed.`));return result}))}return notifications}
