import {lazy,Suspense,type ReactNode} from 'react';import {Navigate,Route,Routes} from 'react-router-dom';import {claims,getTokens} from '../lib/auth';import {AppShell} from '../layouts/AppShell';import {LoginPage} from '../pages/LoginPage';import {AccessibilityLabel} from '../components/ui/AccessibilityLabel';import type {Role} from '../types';
const DashboardPage=lazy(()=>import('../pages/DashboardPage').then(m=>({default:m.DashboardPage})));const PlaybackPage=lazy(()=>import('../pages/PlaybackPage').then(m=>({default:m.PlaybackPage})));const AdminPage=lazy(()=>import('../pages/AdminPage').then(m=>({default:m.AdminPage})));const ClientPage=lazy(()=>import('../pages/ClientPage').then(m=>({default:m.ClientPage})));const VehiclePage=lazy(()=>import('../pages/VehiclePage').then(m=>({default:m.VehiclePage})));
const ReportPage=lazy(()=>import('../pages/ReportPage').then(m=>({default:m.ReportPage})));
const CoinDistributionPage=lazy(()=>import('../pages/CoinDistributionPage').then(m=>({default:m.CoinDistributionPage})));
const GeofencePage=lazy(()=>import('../pages/GeofencePage').then(m=>({default:m.GeofencePage})));
const ConfigureAlertsPage=lazy(()=>import('../pages/AlertPages').then(m=>({default:m.ConfigureAlertsPage})));const NotificationsPage=lazy(()=>import('../pages/AlertPages').then(m=>({default:m.NotificationsPage})));const AnnouncementsPage=lazy(()=>import('../pages/AnnouncementPage').then(m=>({default:m.AnnouncementsPage})));
function Protected(){return getTokens()?<AppShell/>:<Navigate to="/login" replace/>}
function RequireRole({roles,children}:{roles:Role[];children:ReactNode}){return roles.includes(claims()?.role as Role)?children:<Navigate to="/dashboard" replace/>}
export function App(){return <><AccessibilityLabel>Fleet operations application</AccessibilityLabel><Suspense fallback={<div className="route-loader">Loading workspace…</div>}><Routes><Route path="/login" element={<LoginPage/>}/><Route element={<Protected/>}><Route path="/dashboard" element={<DashboardPage/>}/><Route path="/dashboard/playback" element={<PlaybackPage/>}/><Route path="/admin" element={<RequireRole roles={['SUPER_ADMIN','ADMIN']}><AdminPage/></RequireRole>}/><Route path="/clients" element={<RequireRole roles={['SUPER_ADMIN','ADMIN']}><ClientPage/></RequireRole>}/><Route path="/vehicles" element={<RequireRole roles={['SUPER_ADMIN','ADMIN','CLIENT']}><VehiclePage/></RequireRole>}/><Route path="/geofences" element={<GeofencePage/>}/><Route path="/alerts" element={<ConfigureAlertsPage/>}/><Route path="/alerts/notifications" element={<NotificationsPage/>}/><Route path="/alerts/announcements" element={<AnnouncementsPage/>}/><Route path="/reports/coin-distribution" element={<RequireRole roles={['SUPER_ADMIN','ADMIN']}><CoinDistributionPage/></RequireRole>}/><Route path="/reports/distance" element={<ReportPage kind="distance"/>}/><Route path="/reports/ac" element={<ReportPage kind="ac"/>}/><Route path="/reports/packet" element={<ReportPage kind="packet"/>}/><Route path="/reports/travel-summary" element={<ReportPage kind="travel-summary"/>}/><Route path="/reports/daily-trip-summary" element={<ReportPage kind="daily-trip-summary"/>}/><Route path="/reports/status" element={<ReportPage kind="status"/>}/><Route path="/reports/idle" element={<ReportPage kind="idle"/>}/><Route path="/reports/running" element={<ReportPage kind="running"/>}/><Route path="/reports/stoppage" element={<ReportPage kind="stoppage"/>}/><Route path="/reports/overspeed" element={<ReportPage kind="overspeed"/>}/><Route path="/reports/unreachable" element={<ReportPage kind="unreachable"/>}/></Route><Route path="*" element={<Navigate to={getTokens()?'/dashboard':'/login'} replace/>}/></Routes></Suspense></>}
