import {useEffect,useMemo} from 'react';import {CircleMarker,MapContainer,Marker,Polyline,TileLayer,Tooltip,useMap} from 'react-leaflet';import L from 'leaflet';import type {FleetVehicle,PlaybackPoint} from '../../types';import 'leaflet/dist/leaflet.css';
import {renderToStaticMarkup} from 'react-dom/server';
import {VehicleIcon} from '../vehicles/VehicleIcon';
type Point={id:string;latitude:number|null;longitude:number|null;status?:string;label?:string;vehicleType?:string|null};
function Fit({points,selected}:{points:Point[];selected?:Point}){const map=useMap();useEffect(()=>{if(selected?.latitude!=null&&selected.longitude!=null){map.flyTo([selected.latitude,selected.longitude],15,{duration:.55});return}const valid=points.filter(p=>p.latitude!=null&&p.longitude!=null);if(valid.length)map.fitBounds(L.latLngBounds(valid.map(p=>[p.latitude!,p.longitude!])),{padding:[34,34],maxZoom:13})},[map,points,selected]);return null}
function ResizeAwareMap(){const map=useMap();useEffect(()=>{let frame=0;const invalidate=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>map.invalidateSize({animate:false,pan:false}))};invalidate();const container=map.getContainer();const observer=typeof ResizeObserver==='undefined'?null:new ResizeObserver(invalidate);observer?.observe(container);window.addEventListener('resize',invalidate);return()=>{cancelAnimationFrame(frame);observer?.disconnect();window.removeEventListener('resize',invalidate)}},[map]);return null}
function markerIcon(type:string|null|undefined,status='UNREACHABLE',active=false){return L.divIcon({className:`fleet-marker-shell ${active?'active':''}`,html:renderToStaticMarkup(<VehicleIcon type={type} state={status as FleetVehicle['fleet_status']} size="md"/>),iconSize:[42,38],iconAnchor:[21,19]})}
function endpointIcon(kind:'start'|'end'){return L.divIcon({className:'route-endpoint-shell',html:`<span class="route-endpoint ${kind}">${kind==='start'?'S':'E'}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}
export function FleetMap({vehicles,selectedId,onSelect,onHover,mapType='street'}:{vehicles:FleetVehicle[];selectedId:string|null;onSelect:(id:string)=>void;onHover?:(id:string|null)=>void;mapType?:'street'|'satellite'}){const points=useMemo(()=>vehicles.map(v=>({id:v.id,latitude:v.latitude,longitude:v.longitude,status:v.fleet_status,label:v.vehicle_number,vehicleType:v.vehicle_type})),[vehicles]);const selected=points.find(p=>p.id===selectedId);return <MapContainer center={[22.8,79.1]} zoom={5} className="map"><ResizeAwareMap/><TileLayer key={mapType} attribution={mapType==='satellite'?'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community':'&copy; OpenStreetMap contributors'} url={mapType==='satellite'?'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}':'https://tile.openstreetmap.org/{z}/{x}/{y}.png'}/><Fit points={points} selected={selected}/>{points.filter(p=>p.latitude!=null&&p.longitude!=null).map(p=><Marker key={p.id} position={[p.latitude!,p.longitude!]} icon={markerIcon(p.vehicleType,p.status,p.id===selectedId)} eventHandlers={{click:()=>onSelect(p.id),mouseover:()=>onHover?.(p.id),mouseout:()=>onHover?.(null)}}><Tooltip>{p.label}</Tooltip></Marker>)}</MapContainer>}
export function PlaybackMap({points,index,mapType='street'}:{points:PlaybackPoint[];index:number;mapType?:'street'|'satellite'}){const valid=useMemo(()=>points.filter((p):p is PlaybackPoint&{latitude:number;longitude:number}=>p.gps_valid&&p.latitude!=null&&p.longitude!=null),[points]);const active=points[index];const route=valid.map(p=>[p.latitude,p.longitude] as [number,number]);const focus=active?.gps_valid&&active.latitude!=null&&active.longitude!=null?{id:active.id,latitude:active.latitude,longitude:active.longitude}:undefined;const first=valid[0],last=valid.at(-1);return <MapContainer center={[22.8,79.1]} zoom={5} className="map"><ResizeAwareMap/><TileLayer key={mapType} attribution={mapType==='satellite'?'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community':'&copy; OpenStreetMap contributors'} url={mapType==='satellite'?'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}':'https://tile.openstreetmap.org/{z}/{x}/{y}.png'}/><Fit points={valid.map(p=>({id:p.id,latitude:p.latitude,longitude:p.longitude}))} selected={focus}/>{route.length>1&&<Polyline positions={route} pathOptions={{color:'#087ca7',weight:5,opacity:.82}}/>}{valid.map(point=><CircleMarker key={point.id} center={[point.latitude,point.longitude]} radius={2} pathOptions={{color:'#0b4f78',fillColor:'#fff',fillOpacity:.9,weight:1}}/>)}{first&&<Marker position={[first.latitude,first.longitude]} icon={endpointIcon('start')}><Tooltip>Route start</Tooltip></Marker>}{last&&last.id!==first?.id&&<Marker position={[last.latitude,last.longitude]} icon={endpointIcon('end')}><Tooltip>Route end</Tooltip></Marker>}{focus&&<Marker position={[focus.latitude!,focus.longitude!]} icon={markerIcon(null,'RUNNING',true)}><Tooltip>Current playback position</Tooltip></Marker>}</MapContainer>}
