import {useEffect,useState,type FormEvent} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api,errorMessage} from '../../services/api/client';
import {claims} from '../../lib/auth';
import type {Envelope} from '../../types';
import {DataTable,type Column} from '../../components/ui/DataTable';
import {dateTime} from '../../lib/format';
import {PermissionAction} from '../permissions/PermissionAction';
import {PERMISSIONS} from '../../../../../packages/shared-types/src/permissions';
interface Account{id:string;owner_id:string|null;role:string;active:boolean;label:string;balance:string|null}
interface Sale{id:string;distributor_name:string;counterparty_name:string;coins_granted:string;amount_inr:string;payment_reference:string|null;note:string|null;created_at:string}
interface Issuance{monthly_target:string;enforce_hard_cap:boolean;issued:string;timeZone:string}
interface Flow{accounts:Account[];sales:Sale[];total:number;revenue:string;salesCoins:string;issuance:Issuance|null}
const number=(value:string|number)=>Number(value).toLocaleString('en-IN',{maximumFractionDigits:2});
export function CoinManagementPanel({filters}:{filters:{adminId:string;start:string;end:string}}){
 const cache=useQueryClient(),superAdmin=claims()?.role==='SUPER_ADMIN';
 const [page,setPage]=useState(1),[target,setTarget]=useState(''),[coins,setCoins]=useState(''),[rupees,setRupees]=useState(''),[reference,setReference]=useState(''),[note,setNote]=useState(''),[monthly,setMonthly]=useState('0'),[cap,setCap]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>setPage(1),[filters]);
 const flow=useQuery({queryKey:['coin-flow',filters,page],queryFn:async()=>(await api.get<Envelope<Flow>>('/coin-flow',{params:{distributorId:filters.adminId||undefined,start:filters.start,end:filters.end,page,pageSize:25}})).data.data});
 useEffect(()=>{if(flow.data?.issuance){setMonthly(flow.data.issuance.monthly_target);setCap(flow.data.issuance.enforce_hard_cap)}},[flow.data?.issuance?.monthly_target,flow.data?.issuance?.enforce_hard_cap]);
 async function refresh(){await Promise.all([cache.invalidateQueries({queryKey:['coin-flow']}),cache.invalidateQueries({queryKey:['coin-distribution']}),cache.invalidateQueries({queryKey:['admins']}),cache.invalidateQueries({queryKey:['monthly-issuance']}),cache.invalidateQueries({queryKey:['account-summary']})])}
 const sale=useMutation({mutationFn:async()=>api.post('/coin-sales',{counterpartyId:target,coinsGranted:Number(coins),amountInr:Number(rupees),paymentReference:reference,note}),onSuccess:async()=>{setMessage('Payment recorded and coins granted.');setCoins('');setRupees('');setReference('');setNote('');await refresh()}});
 const settings=useMutation({mutationFn:async()=>api.patch('/issuance-settings',{monthlyTarget:Number(monthly),enforceHardCap:cap}),onSuccess:async()=>{setMessage('Monthly issuance settings saved.');await refresh()}});
 const data=flow.data,accounts=data?.accounts??[],recipients=accounts.filter(a=>a.id!==claims()?.id&&a.role!=='SUPER_ADMIN'&&a.active);
 function submit(event:FormEvent){event.preventDefault();setMessage('');sale.mutate()}
 const columns:Column<Sale>[]=[{key:'distributor',label:'Collected by',render:r=>r.distributor_name},{key:'counterparty',label:'Paid by',render:r=>r.counterparty_name},{key:'coins',label:'Coins granted',render:r=>number(r.coins_granted)},{key:'rupees',label:'Amount (INR)',render:r=>'₹'+number(r.amount_inr)},{key:'reference',label:'Payment reference',render:r=>r.payment_reference||'—'},{key:'date',label:'Recorded',render:r=>dateTime(r.created_at)},{key:'note',label:'Note',render:r=>r.note||'—'}];
 function branch(account:Account):React.ReactNode{return <li key={account.id}><span>{account.label} <small>({account.role.replace('_',' ').toLowerCase()})</small></span><strong>{account.role==='SUPER_ADMIN'?'Root issuer':number(account.balance??0)+' coins'}</strong>{accounts.some(a=>a.owner_id===account.id)&&<ul>{accounts.filter(a=>a.owner_id===account.id).map(branch)}</ul>}</li>}
 return <div className="coin-management"><div className="coin-overview"><div><span>Money collected in selected range</span><strong>₹{data?number(data.revenue):'—'}</strong></div><div><span>Coins sold in selected range</span><strong>{data?number(data.salesCoins):'—'}</strong></div>{data?.issuance&&<div><span>This month’s issuance (India time)</span><strong>{number(data.issuance.issued)} / {number(data.issuance.monthly_target)}</strong><small>{data.issuance.enforce_hard_cap?'Monthly cap enabled':'Target for reporting; issuance is unrestricted'}</small></div>}</div>
 {flow.isError&&<div role="alert" className="form-error">{errorMessage(flow.error)}<button type="button" onClick={()=>flow.refetch()}>Retry</button></div>}
 {message&&<div role="status" className="form-success">{message}</div>}
 <div className="coin-forms"><PermissionAction permission={PERMISSIONS.coinDistributionAdd}><form onSubmit={submit}><h2>Record payment and grant coins</h2><p>Record money already collected by cash, UPI, or another method.</p><label>Paid by<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Select account</option>{recipients.map(a=><option key={a.id} value={a.id}>{a.label} ({a.role.toLowerCase()})</option>)}</select></label><label>Coins granted<input required type="number" min="0.01" max="999999999999.99" step="0.01" value={coins} onChange={e=>setCoins(e.target.value)}/></label><label>Amount collected (INR)<input required type="number" min="0.01" max="999999999999.99" step="0.01" value={rupees} onChange={e=>setRupees(e.target.value)}/></label><label>Payment reference<input maxLength={300} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Note<input maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label>{sale.isError&&<div role="alert" className="form-error">{errorMessage(sale.error)}</div>}<button className="button" disabled={sale.isPending||!data}>{sale.isPending?'Saving…':'Record payment'}</button></form></PermissionAction>
 {superAdmin&&<form onSubmit={e=>{e.preventDefault();setMessage('');settings.mutate()}}><h2>Monthly issuance</h2><label>Monthly target<input required type="number" min="0" max="999999999999.99" step="0.01" value={monthly} onChange={e=>setMonthly(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={cap} onChange={e=>setCap(e.target.checked)}/>Enforce monthly cap</label><p>Coins granted to admins and clients expire one year after each grant.</p>{settings.isError&&<div role="alert" className="form-error">{errorMessage(settings.error)}</div>}<button className="button" disabled={settings.isPending||!data}>Save settings</button></form>}</div>
 <details className="coin-tree" open><summary>Current spendable balances</summary><ul>{accounts.filter(a=>!accounts.some(parent=>parent.id===a.owner_id)).map(branch)}</ul></details>
 <h2>Payments received</h2><DataTable columns={columns} rows={data?.sales??[]} emptyMessage={flow.isLoading?'Loading payments…':'No payments recorded in this range'}/><div className="pagination"><span>{data?.total??0} payments</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous payments</button><button disabled={page*25>=(data?.total??0)} onClick={()=>setPage(p=>p+1)}>Next payments</button></div><h2>Coin transaction audit</h2></div>;
}
