import '@testing-library/jest-dom/vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {CoinManagementPanel} from './CoinManagementPanel';
const mocks=vi.hoisted(()=>({id:'root',role:'SUPER_ADMIN',get:vi.fn(),post:vi.fn(),patch:vi.fn()}));
vi.mock('../../lib/auth',()=>({claims:()=>({id:mocks.id,role:mocks.role})}));
vi.mock('../../services/api/client',()=>({api:mocks,errorMessage:()=> 'Insufficient non-expired coin balance'}));
const data={accounts:[{id:'root',owner_id:null,role:'SUPER_ADMIN',active:true,label:'Root',balance:null},{id:'admin',owner_id:'root',role:'ADMIN',active:true,label:'North Admin',balance:'20.00'},{id:'client',owner_id:'admin',role:'CLIENT',active:true,label:'Fleet Client',balance:'5.00'}],sales:[{id:'sale',distributor_name:'North Admin',counterparty_name:'Fleet Client',coins_granted:'5.00',amount_inr:'100.00',payment_reference:'UPI-123',note:'Paid',created_at:'2026-10-04T00:00:00Z'}],total:1,revenue:'100.00',salesCoins:'5.00',issuance:{monthly_target:'1000',enforce_hard_cap:false,issued:'50.00',timeZone:'Asia/Kolkata'}};
function mount(){mocks.get.mockResolvedValue({data:{data:{...data,issuance:mocks.role==='SUPER_ADMIN'?data.issuance:null}}});render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><CoinManagementPanel filters={{adminId:'',start:'2026-10-01T00:00:00Z',end:'2026-10-05T00:00:00Z'}}/></QueryClientProvider>)}
afterEach(()=>{cleanup();vi.clearAllMocks();mocks.role='SUPER_ADMIN';mocks.id='root'});
it('shows cross-tree collections, spendable balances, and monthly issuance',async()=>{mount();expect(await screen.findAllByText('₹100')).toHaveLength(2);expect(screen.getByText('20 coins')).toBeInTheDocument();expect(screen.getByText('5 coins')).toBeInTheDocument();expect(screen.getByText('50 / 1,000')).toBeInTheDocument();expect(screen.getByText('UPI-123')).toBeInTheDocument()});
it('records a cash payment with coins and INR and refreshes the ledger',async()=>{mocks.post.mockResolvedValue({data:{}});mount();await screen.findByText('20 coins');fireEvent.change(screen.getByLabelText('Paid by'),{target:{value:'client'}});fireEvent.change(screen.getByLabelText('Coins granted'),{target:{value:'5'}});fireEvent.change(screen.getByLabelText('Amount collected (INR)'),{target:{value:'100'}});fireEvent.change(screen.getByLabelText('Payment reference'),{target:{value:'UPI-456'}});fireEvent.click(screen.getByRole('button',{name:'Record payment'}));await waitFor(()=>expect(mocks.post).toHaveBeenCalledWith('/coin-sales',{counterpartyId:'client',coinsGranted:5,amountInr:100,paymentReference:'UPI-456',note:''}));expect(await screen.findByText('Payment recorded and coins granted.')).toBeInTheDocument()});
it('limits monthly setting controls to super-admins',async()=>{mocks.role='ADMIN';mount();await screen.findByText('20 coins');expect(screen.queryByLabelText('Monthly target')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Record payment'})).toBeInTheDocument()});
it('prevents an admin from submitting more coins than their available balance',async()=>{mocks.role='ADMIN';mocks.id='admin';mount();await screen.findByText('20 coins');fireEvent.change(screen.getByLabelText('Paid by'),{target:{value:'client'}});fireEvent.change(screen.getByLabelText('Coins granted'),{target:{value:'25'}});fireEvent.change(screen.getByLabelText('Amount collected (INR)'),{target:{value:'100'}});expect(screen.getByRole('alert')).toHaveTextContent('You have 20 available coins');expect(screen.getByLabelText('Coins granted')).toHaveAttribute('aria-invalid','true');expect(screen.getByRole('button',{name:'Record payment'})).toBeDisabled();fireEvent.submit(screen.getByRole('button',{name:'Record payment'}).closest('form')!);expect(mocks.post).not.toHaveBeenCalled()});
it('saves the optional hard cap',async()=>{mocks.patch.mockResolvedValue({data:{}});mount();await screen.findByText('20 coins');fireEvent.change(screen.getByLabelText('Monthly target'),{target:{value:'75'}});fireEvent.click(screen.getByLabelText('Enforce monthly cap'));fireEvent.click(screen.getByRole('button',{name:'Save settings'}));await waitFor(()=>expect(mocks.patch).toHaveBeenCalledWith('/issuance-settings',{monthlyTarget:75,enforceHardCap:true}))});
