import {useEffect,useId,useLayoutEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import './SearchableSelect.css';

export type SelectOption={value:string;label:string};
type Props<T extends string|string[]>={options:SelectOption[];value:T;onChange:(value:T)=>void;placeholder?:string;isDisabled?:boolean;disabled?:boolean;isClearable?:boolean;isLoading?:boolean;isMulti?:boolean;isCreatable?:boolean;name?:string;error?:string;required?:boolean;renderOption?:(option:SelectOption)=>ReactNode;renderValue?:(option:SelectOption)=>ReactNode;renderMultiValue?:(values:string[])=>ReactNode;menuFooter?:ReactNode;renderMenuFooter?:(close:()=>void)=>ReactNode;onSearchChange?:(value:string)=>void;onOpenChange?:(open:boolean)=>void;filterOptions?:boolean;'aria-label'?:string};

export function SearchableSelect<T extends string|string[]>({options,value,onChange,placeholder='Select...',isDisabled,disabled,isClearable=false,isLoading=false,isMulti=false,isCreatable=false,name,error,required=false,renderOption,renderValue,renderMultiValue,menuFooter,renderMenuFooter,onSearchChange,onOpenChange,filterOptions=true,'aria-label':ariaLabel}:Props<T>){
 const id=useId(),root=useRef<HTMLDivElement>(null),searchRef=useRef<HTMLInputElement>(null),[open,setOpen]=useState(false),[search,setSearch]=useState(''),[active,setActive]=useState(0),[rect,setRect]=useState<DOMRect|null>(null);
 const selected:string[]=Array.isArray(value)?value:[value as string],chosen=options.filter(option=>selected.includes(option.value));
 const visible=useMemo(()=>filterOptions?options.filter(option=>option.label.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())):options,[options,search,filterOptions]);
 const close=()=>{setOpen(false);setSearch('');onSearchChange?.('')};
 const choose=(option:SelectOption)=>{if(isMulti){const next=selected.includes(option.value)?selected.filter(item=>item!==option.value):[...selected,option.value];onChange(next as T);setSearch('');searchRef.current?.focus()}else{onChange(option.value as T);close();root.current?.querySelector('button')?.focus()}};
 useLayoutEffect(()=>{if(!open)return;const update=()=>setRect(root.current?.getBoundingClientRect()??null);update();window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true)}},[open]);
 useEffect(()=>{if(!open)return;searchRef.current?.focus();const outside=(event:PointerEvent)=>{const target=event.target as Node;if(!root.current?.contains(target)&&!document.getElementById(id)?.contains(target))close()};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[open,id]);
 useEffect(()=>{onOpenChange?.(open)},[open,onOpenChange]);
 const keyDown=(event:React.KeyboardEvent)=>{if(event.key==='Escape'){event.stopPropagation();close()}else if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();if(!open)setOpen(true);setActive(index=>Math.max(0,Math.min(visible.length-1,index+(event.key==='ArrowDown'?1:-1))))}else if(event.key==='Enter'&&open){event.preventDefault();if(visible[active])choose(visible[active]);else if(isCreatable&&search.trim())choose({value:search.trim(),label:search.trim()})}else if(event.key==='Tab')close()};
 return <div ref={root} className={`searchable-select${open?' is-open':''}${error?' has-error':''}`} onKeyDown={keyDown}>
  <button type="button" role="combobox" aria-label={ariaLabel} aria-controls={id} aria-expanded={open} aria-haspopup="listbox" disabled={isDisabled||disabled} className="searchable-select-trigger" onClick={()=>{if(open)close();else setOpen(true);setActive(0)}}>
   <span className={chosen.length||(isMulti&&selected.length)||(isCreatable&&selected[0])?'searchable-select-value':'searchable-select-placeholder'}>{isMulti&&selected.length&&renderMultiValue?renderMultiValue(selected):isMulti&&chosen.length?<span className="searchable-select-chips">{chosen.map(option=><span className="searchable-select-chip" key={option.value}>{option.label}<span role="button" tabIndex={0} aria-label={`Remove ${option.label}`} onClick={event=>{event.stopPropagation();onChange(selected.filter(item=>item!==option.value) as T)}} onKeyDown={event=>{if(event.key==='Enter'){event.stopPropagation();onChange(selected.filter(item=>item!==option.value) as T)}}}>×</span></span>)}</span>:chosen[0]?(renderValue?.(chosen[0])??chosen[0].label):(isCreatable&&selected[0]?selected[0]:placeholder)}</span><span className={`searchable-select-caret${open?' up':''}`}/>
  </button>
  {name&&<input type="hidden" name={name} value={selected.join(',')}/>} {required&&<input className="searchable-select-required" tabIndex={-1} aria-label={ariaLabel} required value={selected.length&&selected[0]?selected.join(','):''} onChange={()=>{}} onInvalid={()=>setOpen(true)}/>}
  {open&&rect&&createPortal(<div id={id} className="searchable-select-menu" style={{position:'fixed',left:rect.left,top:rect.bottom+2,width:rect.width,zIndex:5000}}><input ref={searchRef} aria-label={`Search ${ariaLabel||placeholder}`} value={search} onChange={event=>{setSearch(event.target.value);setActive(0);onSearchChange?.(event.target.value)}} placeholder="Search..."/><div role="listbox" aria-label={ariaLabel} aria-multiselectable={isMulti||undefined} className="searchable-select-options">{isLoading?<div className="searchable-select-empty">Loading...</div>:visible.length?visible.map((option,index)=><button type="button" role="option" aria-selected={selected.includes(option.value)} className={index===active||selected.includes(option.value)?'highlighted':''} key={option.value} onMouseEnter={()=>setActive(index)} onClick={()=>choose(option)}>{renderOption?.(option)??option.label}</button>):isCreatable&&search.trim()?<button type="button" role="option" aria-selected={false} onClick={()=>choose({value:search.trim(),label:search.trim()})}>Use {search.trim()}</button>:<div className="searchable-select-empty">{options.length?'No results found':'No options'}</div>}</div>{menuFooter}{renderMenuFooter?.(close)}{isClearable&&selected.some(Boolean)&&<button type="button" className="searchable-select-clear" onClick={()=>{onChange((isMulti?[]:'') as T);close()}}>Clear selection</button>}</div>,document.body)}
  {error&&<span className="searchable-select-error">{error}</span>}
 </div>
}
