import '@testing-library/jest-dom/vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {ClientModal} from './ClientModal';
const mocks=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),patch:vi.fn()}));
mocks.get.mockResolvedValue({data:{data:[{id:'admin-1',name:'Admin A',username:'admin.a',email:'admin@test.local'}]}});
vi.mock('../../services/api/client',()=>({api:mocks,errorMessage:()=> 'error'}));
afterEach(cleanup);
it('loads authorized admins and requires secure create fields',async()=>{render(<QueryClientProvider client={new QueryClient()}><ClientModal open client={null} onClose={()=>undefined}/></QueryClientProvider>);expect(await screen.findByRole('option',{name:'Admin A'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Save client'}));expect(mocks.post).not.toHaveBeenCalled();expect(screen.getByLabelText('Owner')).toBeRequired();expect(screen.getByLabelText('Username')).toBeRequired();expect(screen.getByLabelText('Password')).toHaveAttribute('minLength','8');expect(screen.getByLabelText('Email')).toHaveAttribute('type','email')});
