import {useState,type FormEvent} from 'react';
import {useMutation} from '@tanstack/react-query';
import {LoaderCircle} from 'lucide-react';
import {Modal} from '../../components/ui/Modal';
import {Button} from '../../components/ui/Button';
import {api,errorMessage} from '../../services/api/client';
import type {Client} from '../../types';

export function ResetPasswordModal({client,onClose}:{client:Client|null;onClose:()=>void}){const [password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState('');const mutation=useMutation({mutationFn:()=>api.post(`/clients/${client!.id}/reset-password`,{password,confirmPassword}),onSuccess:()=>{setPassword('');setConfirmPassword('');onClose()}});function submit(event:FormEvent){event.preventDefault();if(password!==confirmPassword)return;mutation.mutate()}return <Modal open={Boolean(client)} title="Reset client password" onClose={onClose}><form className="admin-form reset-form" onSubmit={submit}><p className="wide reset-note">Set a new password for <strong>{client?.username||client?.email}</strong>. The existing password is never shown.</p><label className="wide">New password<input aria-label="New password" required minLength={8} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="wide">Confirm password<input aria-label="Confirm password" required minLength={8} type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>{confirmPassword&&password!==confirmPassword&&<div className="form-error wide" role="alert">Passwords do not match.</div>}{mutation.isError&&<div className="form-error wide" role="alert">{errorMessage(mutation.error)}</div>}<footer className="wide"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><Button disabled={mutation.isPending||password!==confirmPassword}>{mutation.isPending?<><LoaderCircle className="spin"/>Resetting…</>:'Reset password'}</Button></footer></form></Modal>}
