export interface HistoryPoint {id:string;vehicle_id:string;tracker_timestamp:string|Date|null;server_received_at:string|Date;latitude:number|null;longitude:number|null;speed:number|null;ignition:boolean|null;gps_valid:boolean;ac:boolean|null}
export type MotionState='running'|'idle'|'stop'|'unreachable';
export interface Summary {km:number;runningSeconds:number;idleSeconds:number;stopSeconds:number;unreachableSeconds:number;tripCount:number;idleCount:number;stopCount:number;unreachableCount:number;maxSpeed:number|null;avgSpeed:number|null;startPoint:HistoryPoint|null;endPoint:HistoryPoint|null}
export const pointDate=(point:HistoryPoint)=>new Date(point.tracker_timestamp||point.server_received_at);
export const validPosition=(point:HistoryPoint)=>point.gps_valid&&point.latitude!=null&&point.longitude!=null&&Number.isFinite(point.latitude)&&Number.isFinite(point.longitude);
export function haversineKm(a:HistoryPoint,b:HistoryPoint){if(!validPosition(a)||!validPosition(b))return 0;const rad=Math.PI/180,dLat=(b.latitude!-a.latitude!)*rad,dLon=(b.longitude!-a.longitude!)*rad;const x=Math.sin(dLat/2)**2+Math.cos(a.latitude!*rad)*Math.cos(b.latitude!*rad)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
export function motionState(point:HistoryPoint,movementThreshold:number):MotionState {if(point.speed!=null&&point.speed>movementThreshold)return'running';if(point.ignition===true)return'idle';if(point.ignition===false)return'stop';return'unreachable'}
export function summarize(points:HistoryPoint[],movementThreshold:number,offlineTimeoutSeconds:number):Summary {const ordered=[...points].sort((a,b)=>+pointDate(a)-+pointDate(b));const positions=ordered.filter(validPosition);let km=0;for(let i=1;i<positions.length;i++)km+=haversineKm(positions[i-1],positions[i]);const seconds:Record<MotionState,number>={running:0,idle:0,stop:0,unreachable:0},counts:Record<MotionState,number>={running:0,idle:0,stop:0,unreachable:0};let previous:MotionState|null=null;for(let i=0;i<ordered.length-1;i++){const elapsed=Math.max(0,(+pointDate(ordered[i+1])-+pointDate(ordered[i]))/1000);const state=motionState(ordered[i],movementThreshold);const known=Math.min(elapsed,offlineTimeoutSeconds);seconds[state]+=known;if(state!==previous){counts[state]++;previous=state}if(elapsed>offlineTimeoutSeconds){seconds.unreachable+=elapsed-offlineTimeoutSeconds;if(previous!=='unreachable'){counts.unreachable++;previous='unreachable'}}}const speeds=ordered.map(point=>point.speed).filter((value):value is number=>value!=null&&Number.isFinite(value)&&value>=0);return{km,runningSeconds:seconds.running,idleSeconds:seconds.idle,stopSeconds:seconds.stop,unreachableSeconds:seconds.unreachable,tripCount:counts.running,idleCount:counts.idle,stopCount:counts.stop,unreachableCount:counts.unreachable,maxSpeed:speeds.length?Math.max(...speeds):null,avgSpeed:speeds.length?speeds.reduce((sum,value)=>sum+value,0)/speeds.length:null,startPoint:positions[0]||null,endPoint:positions.at(-1)||null}}
export function acSessions(points:HistoryPoint[],rangeStart:Date,rangeEnd:Date){const ordered=[...points].filter(point=>point.ac!=null).sort((a,b)=>+pointDate(a)-+pointDate(b));const sessions:Array<{status:'ON';startTime:string;endTime:string;durationSeconds:number;startPoint:HistoryPoint;endPoint:HistoryPoint}>=[];let start:HistoryPoint|null=null;for(const point of ordered){if(point.ac===true&&!start)start=point;if(point.ac===false&&start){const from=new Date(Math.max(+rangeStart,+pointDate(start))),to=new Date(Math.min(+rangeEnd,+pointDate(point)));if(to>from)sessions.push({status:'ON',startTime:from.toISOString(),endTime:to.toISOString(),durationSeconds:(+to-+from)/1000,startPoint:start,endPoint:point});start=null}}if(start){const from=new Date(Math.max(+rangeStart,+pointDate(start)));if(rangeEnd>from)sessions.push({status:'ON',startTime:from.toISOString(),endTime:rangeEnd.toISOString(),durationSeconds:(+rangeEnd-+from)/1000,startPoint:start,endPoint:ordered.at(-1)!})}return sessions}
export function localDateKey(date:Date,timeZone:string){const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),value=(type:string)=>parts.find(part=>part.type===type)!.value;return`${value('year')}-${value('month')}-${value('day')}`}
