import {AppError} from '../../lib/errors.js';
import {env} from '../../config/env.js';
import {acSessions,haversineKm,localDateKey,pointDate,stateSessions,summarize,unreachableSessions,type HistoryPoint,type HistorySession} from './calculations.js';
import {reportHistory,reportVehicles} from './repository.js';
export interface ReportQuery {vehicleId?:string;search:string;page:number;pageSize:number;start:Date;end:Date;timeZone:string;sort:string;order:'asc'|'desc'}
const position=(point:HistoryPoint|null)=>point?.gps_valid&&point.latitude!=null&&point.longitude!=null?{latitude:point.latitude,longitude:point.longitude}:null;
const pointAddress=(point:HistoryPoint|null)=>{const value=point?.metadata?.address;return typeof value==='string'&&value.trim()?value.trim():null};
const duration=(seconds:number)=>Math.round(seconds);
function groupBy<K,V>(items:V[],key:(item:V)=>K){const result=new Map<K,V[]>();for(const item of items){const value=key(item);result.set(value,[...(result.get(value)||[]),item])}return result}
const grouped=(points:HistoryPoint[])=>groupBy(points,point=>point.vehicle_id);
async function context(actorId:string,q:ReportQuery,previous=false){const vehicles=await reportVehicles(actorId,q);if(q.pageSize===10000&&Number(vehicles.rows[0]?.total_count??0)>10000)throw new AppError(413,'REPORT_TOO_LARGE','Narrow the vehicle filters');if(q.vehicleId&&!vehicles.rows.length)throw new AppError(404,'VEHICLE_NOT_FOUND','Vehicle not found');const history=await reportHistory(actorId,vehicles.rows.map(v=>v.id),q.start,q.end,previous);if(history.rows.length>250000)throw new AppError(413,'REPORT_TOO_LARGE','Narrow the vehicle or date filters');return{vehicles:vehicles.rows,points:grouped(history.rows),total:Number(vehicles.rows[0]?.total_count??0)}}
const stats=(points:HistoryPoint[])=>summarize(points,env.MOVEMENT_THRESHOLD_KPH,env.OFFLINE_TIMEOUT_SECONDS);
function sortRows<T extends Record<string,unknown>>(rows:T[],q:ReportQuery){return[...rows].sort((a,b)=>{const left=a[q.sort],right=b[q.sort],result=typeof left==='number'&&typeof right==='number'?left-right:String(left??'').localeCompare(String(right??''));return q.order==='asc'?result:-result})}
export async function distanceReport(actorId:string,q:ReportQuery){const c=await context(actorId,{...q,page:1,pageSize:10000});const dates:string[]=[];for(let cursor=new Date(q.start);cursor<q.end;cursor=new Date(+cursor+86400000)){const key=localDateKey(cursor,q.timeZone);if(!dates.includes(key))dates.push(key)}const vehicles=c.vehicles.filter(v=>(c.points.get(v.id)||[]).length);return{rows:vehicles.slice((q.page-1)*q.pageSize,q.page*q.pageSize).map(v=>{const byDay=groupBy(c.points.get(v.id)||[],point=>localDateKey(pointDate(point),q.timeZone));return{id:v.id,vehicleNumber:v.vehicle_number,alias:v.alias,distances:Object.fromEntries(dates.map(day=>[day,Number(stats(byDay.get(day)||[]).km.toFixed(2))]))}}),dates,total:vehicles.length}}
export async function travelReport(actorId:string,q:ReportQuery){const c=await context(actorId,{...q,page:1,pageSize:10000}),vehicles=c.vehicles.filter(v=>(c.points.get(v.id)||[]).length);return{rows:vehicles.slice((q.page-1)*q.pageSize,q.page*q.pageSize).map(v=>{const s=stats(c.points.get(v.id)||[]);return{id:v.id,vehicleNumber:v.vehicle_number,alias:v.alias,km:Number(s.km.toFixed(2)),running:duration(s.runningSeconds),tripCount:s.tripCount,idle:duration(s.idleSeconds),idleCount:s.idleCount,stop:duration(s.stopSeconds),stopCount:s.stopCount,unreachable:duration(s.unreachableSeconds),unreachableCount:s.unreachableCount,maxSpeed:s.maxSpeed,avgSpeed:s.avgSpeed}}),total:vehicles.length}}
export async function dailyReport(actorId:string,q:ReportQuery){const c=await context(actorId,{...q,page:1,pageSize:10000}),vehicles=c.vehicles.filter(v=>(c.points.get(v.id)||[]).length);return{rows:vehicles.slice((q.page-1)*q.pageSize,q.page*q.pageSize).map(v=>{const s=stats(c.points.get(v.id)||[]);return{id:v.id,vehicleNumber:v.vehicle_number,alias:v.alias,km:Number(s.km.toFixed(2)),running:duration(s.runningSeconds),idle:duration(s.idleSeconds),stop:duration(s.stopSeconds),unreachable:duration(s.unreachableSeconds),startLocation:position(s.startPoint),startAddress:pointAddress(s.startPoint),endLocation:position(s.endPoint),endAddress:pointAddress(s.endPoint),maxSpeed:s.maxSpeed,avgSpeed:s.avgSpeed,playbackAvailable:Boolean(s.startPoint&&s.endPoint&&s.startPoint.id!==s.endPoint.id)}}),total:vehicles.length}}
export async function acReport(actorId:string,q:ReportQuery){const c=await context(actorId,{...q,page:1,pageSize:10000},true);const rows=c.vehicles.flatMap(v=>acSessions(c.points.get(v.id)||[],q.start,q.end).map((session,index)=>({id:`${v.id}-${index}`,vehicleId:v.id,vehicleNumber:v.vehicle_number,...session,startLocation:position(session.startPoint),startAddress:pointAddress(session.startPoint),endLocation:position(session.endPoint),endAddress:pointAddress(session.endPoint)}))),sorted=sortRows(rows,q),start=(q.page-1)*q.pageSize;return{rows:sorted.slice(start,start+q.pageSize),total:rows.length}}
export async function packetReport(actorId:string,q:ReportQuery,intervalHours:number){const c=await context(actorId,{...q,page:1,pageSize:10000});const bucketMs=intervalHours*3600000,rows=[];let sn=1;for(const vehicle of c.vehicles){const points=c.points.get(vehicle.id)||[];for(let from=+q.start;from<+q.end;from+=bucketMs){const to=Math.min(+q.end,from+bucketMs),bucket=points.filter(p=>+pointDate(p)>=from&&+pointDate(p)<to);if(!bucket.length)continue;const s=stats(bucket);rows.push({id:`${vehicle.id}-${from}`,sn:sn++,vehicleId:vehicle.id,vehicleNumber:vehicle.vehicle_number,rangeStart:new Date(from).toISOString(),rangeEnd:new Date(to).toISOString(),km:Number(s.km.toFixed(2)),duration:bucket.length>1?Math.max(0,(+pointDate(bucket.at(-1)!)-+pointDate(bucket[0]))/1000):0,packetCount:bucket.length,firstPacket:pointDate(bucket[0]).toISOString(),firstLocation:position(bucket[0]),firstAddress:pointAddress(bucket[0]),lastPacket:pointDate(bucket.at(-1)!).toISOString(),lastLocation:position(bucket.at(-1)!),lastAddress:pointAddress(bucket.at(-1)!),maxSpeed:s.maxSpeed,avgSpeed:s.avgSpeed,playbackAvailable:bucket.filter(p=>p.latitude!=null&&p.longitude!=null).length>1})}}const sorted=sortRows(rows,q),start=(q.page-1)*q.pageSize;return{rows:sorted.slice(start,start+q.pageSize),total:rows.length}}

export type StatusFilter='IGNITION_ON'|'IGNITION_OFF'|'IDLE'|'OVERSPEED'|'UNREACHABLE'|'AC_ON'|'RUNNING'|'STOPPED';
type VehicleContext=Awaited<ReturnType<typeof context>>['vehicles'][number];
function sessionRow(vehicle:VehicleContext,session:HistorySession,index:number){const s=stats(session.points);return{id:`${vehicle.id}-${session.startTime}-${index}`,vehicleId:vehicle.id,vehicleNumber:vehicle.vehicle_number,startTime:session.startTime,endTime:session.endTime,durationSeconds:duration(session.durationSeconds),km:Number(s.km.toFixed(2)),startLocation:position(session.startPoint),startAddress:pointAddress(session.startPoint),endLocation:position(session.endPoint),endAddress:pointAddress(session.endPoint),location:position(session.startPoint),address:pointAddress(session.startPoint),maxSpeed:s.maxSpeed,avgSpeed:s.avgSpeed,playbackAvailable:session.points.filter(p=>p.gps_valid&&p.latitude!=null&&p.longitude!=null).length>1}}
function predicate(kind:Exclude<StatusFilter,'UNREACHABLE'>,vehicle:VehicleContext){return(point:HistoryPoint)=>{const moving=point.speed!=null&&point.speed>env.MOVEMENT_THRESHOLD_KPH;if(kind==='IGNITION_ON')return point.ignition===true;if(kind==='IGNITION_OFF')return point.ignition===false;if(kind==='RUNNING')return moving;if(kind==='STOPPED')return point.ignition===false&&!moving;if(kind==='IDLE')return point.ignition===true&&!moving;if(kind==='AC_ON')return point.ac===true;return vehicle.overspeed_limit!=null&&point.speed!=null&&point.speed>vehicle.overspeed_limit}}
function sessionsFor(kind:StatusFilter,vehicle:VehicleContext,points:HistoryPoint[],q:ReportQuery){return kind==='UNREACHABLE'?unreachableSessions(points,q.start,q.end,env.NO_SIGNAL_TIMEOUT_MINUTES*60):stateSessions(points,q.start,q.end,predicate(kind,vehicle),env.OFFLINE_TIMEOUT_SECONDS)}
async function sessionReport(actorId:string,q:ReportQuery,kind:StatusFilter){const c=await context(actorId,{...q,page:1,pageSize:10000},true),all=c.vehicles.flatMap(vehicle=>sessionsFor(kind,vehicle,c.points.get(vehicle.id)||[],q).map((session,index)=>({...sessionRow(vehicle,session,index),status:kind}))),sorted=sortRows(all,q);const start=(q.page-1)*q.pageSize;return{rows:sorted.slice(start,start+q.pageSize),total:all.length}}
export const statusReport=(actorId:string,q:ReportQuery,status:StatusFilter)=>sessionReport(actorId,q,status);
export const idleReport=(actorId:string,q:ReportQuery)=>sessionReport(actorId,q,'IDLE');
export async function runningReport(actorId:string,q:ReportQuery){return sessionReport(actorId,q,'RUNNING')}
export async function overspeedReport(actorId:string,q:ReportQuery){return sessionReport(actorId,q,'OVERSPEED')}
export async function unreachableReport(actorId:string,q:ReportQuery){return sessionReport(actorId,q,'UNREACHABLE')}
export async function stoppageReport(actorId:string,q:ReportQuery){const c=await context(actorId,{...q,page:1,pageSize:10000},true),all=c.vehicles.flatMap(vehicle=>{let previous:ReturnType<typeof sessionRow>|undefined;return sessionsFor('STOPPED',vehicle,c.points.get(vehicle.id)||[],q).map((session,index)=>{const row=sessionRow(vehicle,session,index),kmFromLast=previous&&row.startLocation&&previous.endLocation?haversineKm({...({gps_valid:true} as HistoryPoint),id:'a',vehicle_id:row.vehicleId,tracker_timestamp:row.startTime,server_received_at:row.startTime,speed:null,ignition:null,ac:null,...previous.endLocation},{...({gps_valid:true} as HistoryPoint),id:'b',vehicle_id:row.vehicleId,tracker_timestamp:row.startTime,server_received_at:row.startTime,speed:null,ignition:null,ac:null,...row.startLocation}):null,duFromLast=previous?(+new Date(row.startTime)-+new Date(previous.endTime))/1000:null;previous=row;return{...row,kmFromLast:kmFromLast==null?null:Number(kmFromLast.toFixed(2)),duFromLast}})}),sorted=sortRows(all,q),start=(q.page-1)*q.pageSize;return{rows:sorted.slice(start,start+q.pageSize),total:all.length}}
