import {AppError} from '../../lib/errors.js';
import {env} from '../../config/env.js';
import {acSessions,localDateKey,pointDate,summarize,type HistoryPoint} from './calculations.js';
import {reportHistory,reportVehicles} from './repository.js';
export interface ReportQuery {vehicleId?:string;search:string;page:number;pageSize:number;start:Date;end:Date;timeZone:string}
const position=(point:HistoryPoint|null)=>point&&point.latitude!=null&&point.longitude!=null?{latitude:point.latitude,longitude:point.longitude}:null;
const duration=(seconds:number)=>Math.round(seconds);
function groupBy<K,V>(items:V[],key:(item:V)=>K){const result=new Map<K,V[]>();for(const item of items){const value=key(item);result.set(value,[...(result.get(value)||[]),item])}return result}
const grouped=(points:HistoryPoint[])=>groupBy(points,point=>point.vehicle_id);
async function context(actorId:string,q:ReportQuery,previous=false){const vehicles=await reportVehicles(actorId,q);if(q.vehicleId&&!vehicles.rows.length)throw new AppError(404,'VEHICLE_NOT_FOUND','Vehicle not found');const history=await reportHistory(actorId,vehicles.rows.map(v=>v.id),q.start,q.end,previous);if(history.rows.length>250000)throw new AppError(413,'REPORT_TOO_LARGE','Narrow the vehicle or date filters');return{vehicles:vehicles.rows,points:grouped(history.rows),total:Number(vehicles.rows[0]?.total_count??0)}}
const stats=(points:HistoryPoint[])=>summarize(points,env.MOVEMENT_THRESHOLD_KPH,env.OFFLINE_TIMEOUT_SECONDS);
export async function distanceReport(actorId:string,q:ReportQuery){const c=await context(actorId,q);const dates:string[]=[];for(let cursor=new Date(q.start);cursor<q.end;cursor=new Date(+cursor+86400000)){const key=localDateKey(cursor,q.timeZone);if(!dates.includes(key))dates.push(key)}const vehicles=c.vehicles.filter(v=>(c.points.get(v.id)||[]).length);return{rows:vehicles.map(v=>{const byDay=groupBy(c.points.get(v.id)||[],point=>localDateKey(pointDate(point),q.timeZone));return{id:v.id,vehicleNumber:v.vehicle_number,alias:v.alias,distances:Object.fromEntries(dates.map(day=>[day,Number(stats(byDay.get(day)||[]).km.toFixed(2))]))}}),dates,total:vehicles.length}}
export async function travelReport(actorId:string,q:ReportQuery){const c=await context(actorId,q),vehicles=c.vehicles.filter(v=>(c.points.get(v.id)||[]).length);return{rows:vehicles.map(v=>{const s=stats(c.points.get(v.id)||[]);return{id:v.id,vehicleNumber:v.vehicle_number,alias:v.alias,km:Number(s.km.toFixed(2)),running:duration(s.runningSeconds),tripCount:s.tripCount,idle:duration(s.idleSeconds),idleCount:s.idleCount,stop:duration(s.stopSeconds),stopCount:s.stopCount,unreachable:duration(s.unreachableSeconds),unreachableCount:s.unreachableCount,maxSpeed:s.maxSpeed,avgSpeed:s.avgSpeed}}),total:vehicles.length}}
export async function dailyReport(actorId:string,q:ReportQuery){const c=await context(actorId,q),vehicles=c.vehicles.filter(v=>(c.points.get(v.id)||[]).length);return{rows:vehicles.map(v=>{const s=stats(c.points.get(v.id)||[]);return{id:v.id,vehicleNumber:v.vehicle_number,alias:v.alias,km:Number(s.km.toFixed(2)),running:duration(s.runningSeconds),idle:duration(s.idleSeconds),stop:duration(s.stopSeconds),unreachable:duration(s.unreachableSeconds),startLocation:position(s.startPoint),startAddress:null,endLocation:position(s.endPoint),endAddress:null,maxSpeed:s.maxSpeed,avgSpeed:s.avgSpeed,playbackAvailable:Boolean(s.startPoint&&s.endPoint&&s.startPoint.id!==s.endPoint.id)}}),total:vehicles.length}}
export async function acReport(actorId:string,q:ReportQuery){const c=await context(actorId,q,true);const rows=c.vehicles.flatMap(v=>acSessions(c.points.get(v.id)||[],q.start,q.end).map((session,index)=>({id:`${v.id}-${index}`,vehicleId:v.id,vehicleNumber:v.vehicle_number,...session,startLocation:position(session.startPoint),startAddress:null,endLocation:position(session.endPoint),endAddress:null})));return{rows,total:rows.length}}
export async function packetReport(actorId:string,q:ReportQuery,intervalHours:number){if(!q.vehicleId)return{rows:[],total:0};const c=await context(actorId,{...q,page:1,pageSize:1});const points=c.points.get(q.vehicleId)||[];if(!points.length)return{rows:[],total:0};const bucketMs=intervalHours*3600000,rows=[];let sn=1;for(let from=+q.start;from<+q.end;from+=bucketMs){const to=Math.min(+q.end,from+bucketMs),bucket=points.filter(p=>+pointDate(p)>=from&&+pointDate(p)<to);if(!bucket.length)continue;const s=stats(bucket);rows.push({id:`${q.vehicleId}-${from}`,sn:sn++,vehicleId:q.vehicleId,rangeStart:new Date(from).toISOString(),rangeEnd:new Date(to).toISOString(),km:Number(s.km.toFixed(2)),duration:bucket.length>1?Math.max(0,(+pointDate(bucket.at(-1)!)-+pointDate(bucket[0]))/1000):0,packetCount:bucket.length,firstPacket:pointDate(bucket[0]).toISOString(),firstLocation:position(bucket[0]),firstAddress:null,lastPacket:pointDate(bucket.at(-1)!).toISOString(),lastLocation:position(bucket.at(-1)!),lastAddress:null,maxSpeed:s.maxSpeed,avgSpeed:s.avgSpeed,playbackAvailable:bucket.filter(p=>p.latitude!=null&&p.longitude!=null).length>1})}return{rows,total:rows.length}}
