import '@testing-library/jest-dom/vitest';
import type {ReactNode} from 'react';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {DashboardPage,mergeDashboardTelemetry,withDashboardPreviewTelemetry} from './DashboardPage';
import type {FleetVehicle} from '../types';
const mocks=vi.hoisted(()=>({get:vi.fn()}));
vi.mock('../services/api/client',()=>({api:{get:mocks.get},errorMessage:()=> 'error'}));
vi.mock('../lib/auth',()=>({getTokens:()=>null,claims:()=>({role:'ADMIN'})}));
vi.mock('../features/map/MapSurface',()=>({FleetMap:()=> <div data-testid="map"/>}));
vi.mock('socket.io-client',()=>({io:()=>({on:vi.fn(),disconnect:vi.fn()})}));
const vehicle:FleetVehicle={id:'v1',vehicle_number:'HR12AV4151',alias:'North route',vehicle_type:'truck',active:true,overspeed_limit:80,owner_id:'u1',owner_email:'ops@test.local',device_id:'d1',last_seen_at:'2026-09-16T10:00:00Z',state:'MOVING',tracker_timestamp:'2026-09-16T10:00:00Z',server_received_at:'2026-09-16T10:00:00Z',latitude:28.87,longitude:76.62,speed:44,ignition:true,fleet_status:'RUNNING',address:null,status_since_at:'2026-09-16T09:55:00Z',today_distance_km:12.4,today_running_seconds:1800,today_stopped_seconds:300,today_avg_speed:32,today_max_speed:61,distance_from_last_stop_km:4.2,duration_from_last_stop_seconds:900,duration_at_last_stop_seconds:null};
const wrapper=(ui:ReactNode)=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter>{ui}</MemoryRouter></QueryClientProvider>);
afterEach(cleanup);
describe('dashboard',()=>{beforeEach(()=>mocks.get.mockReset());it('renders API rows, changes the server filter, and expands the selected vehicle details upward',async()=>{mocks.get.mockResolvedValue({data:{success:true,data:[vehicle],counts:{ALL:1,OVERSPEED:0,RUNNING:1,IDLE:0,STOPPED:0,UNREACHABLE:0,NEW:0,INACTIVE:0},pagination:{page:1,pageSize:25,total:1}}});wrapper(<DashboardPage/>);expect(await screen.findByText('HR12AV4151')).toBeInTheDocument();fireEvent.click(screen.getByText('HR12AV4151'));const summary=screen.getByRole('region',{name:'HR12AV4151 details'});expect(summary.querySelector('.summary-address')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Expand vehicle details'})).toHaveAttribute('aria-expanded','false');fireEvent.click(screen.getByRole('button',{name:'Expand vehicle details'}));expect(screen.getByRole('button',{name:'Collapse vehicle details'})).toHaveAttribute('aria-expanded','true');expect(summary).toHaveClass('expanded');expect(summary.querySelector('.summary-address')).toBeInTheDocument();fireEvent.click(screen.getByText('Stopped'));await waitFor(()=>expect(mocks.get).toHaveBeenLastCalledWith('/dashboard/vehicles',expect.objectContaining({params:expect.objectContaining({status:'STOPPED'})}))) });it('shows an honest empty state without demo fallback',async()=>{mocks.get.mockResolvedValue({data:{success:true,data:[],counts:{ALL:0,OVERSPEED:0,RUNNING:0,IDLE:0,STOPPED:0,UNREACHABLE:0,NEW:0,INACTIVE:0},pagination:{page:1,pageSize:25,total:0}}});wrapper(<DashboardPage/>);expect(await screen.findByText('No vehicles found')).toBeInTheDocument();expect(screen.queryByText('HR12AV4151')).not.toBeInTheDocument()})});
describe('dashboard panel controls',()=>{beforeEach(()=>mocks.get.mockResolvedValue({data:{success:true,data:[vehicle],counts:{ALL:1,OVERSPEED:0,RUNNING:1,IDLE:0,STOPPED:0,UNREACHABLE:0,NEW:0,INACTIVE:0},pagination:{page:1,pageSize:25,total:1}}}));it('keeps the map mounted while resizing and provides the fixed admin columns and panel controls',async()=>{wrapper(<DashboardPage/>);await screen.findByText('HR12AV4151');expect(screen.getAllByRole('columnheader').map(cell=>cell.textContent?.replace(/[\u2195\u2191\u2193]/g,''))).toEqual(['SN','Status','Vehicle','Client','Speed','GPS','Since','TodayKm','TodayDu','Address']);expect(screen.queryByRole('button',{name:'Configure columns'})).not.toBeInTheDocument();expect(screen.getByText('Showing 1 to 1 of 1 entries')).toBeVisible();expect(screen.queryByRole('button',{name:'Export dashboard PDF'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Export dashboard Excel'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Refresh/})).not.toBeInTheDocument();const map=screen.getByTestId('map'),separator=screen.getByRole('separator',{name:'Resize table and map'});expect(separator).toHaveAttribute('aria-valuenow','48');fireEvent.keyDown(separator,{key:'ArrowRight'});expect(separator).toHaveAttribute('aria-valuenow','50');fireEvent.click(screen.getByRole('button',{name:'Table fullscreen'}));expect(screen.getByRole('button',{name:'Exit table fullscreen'})).toHaveAttribute('aria-pressed','true');expect(screen.getByTestId('map')).toBe(map);fireEvent.click(screen.getByRole('button',{name:'Exit table fullscreen'}));fireEvent.click(screen.getByRole('button',{name:'Map fullscreen'}));expect(screen.getByRole('button',{name:'Exit map fullscreen'})).toHaveAttribute('aria-pressed','true');fireEvent.click(screen.getByRole('button',{name:'Map settings'}));const satellite=screen.getByRole('switch',{name:'Satellite'});expect(satellite).not.toBeChecked();fireEvent.click(satellite);expect(satellite).toBeChecked()})});

describe('dashboard real telemetry',()=>{it('never substitutes demo positions or addresses for missing GPS data',()=>{const missing={...vehicle,latitude:null,longitude:null,speed:null,address:null,today_distance_km:null};expect(withDashboardPreviewTelemetry([missing,vehicle])).toEqual([missing,vehicle])})});

it('retains the last GPS address on invalid fixes while applying idle status',()=>{
 const previous={...vehicle,address:'Rohtak road',address_attribution:'Geoapify'};
 const next=mergeDashboardTelemetry(previous,{gps_valid:false,latitude:0,longitude:0,address:null,speed:0,fleet_status:'IDLE'});
 expect(next).toMatchObject({latitude:previous.latitude,longitude:previous.longitude,address:previous.address,tracker_timestamp:previous.tracker_timestamp,speed:0,fleet_status:'IDLE'});
 expect(mergeDashboardTelemetry(previous,{gpsValid:false,latitude:0,longitude:0,address:null}).address).toBe(previous.address);
 expect(mergeDashboardTelemetry(previous,{gps_valid:true,latitude:29,address:null}).address).toBeNull();
});

it('accepts a cell address even when GPS has no fix',()=>{
 const previous={...vehicle,address:'Cell area (approx.): Old',address_source:'cell' as const};
 expect(mergeDashboardTelemetry(previous,{gpsValid:false,latitude:0,longitude:0,address_source:'cell',address:'Cell area (approx.): New'})).toMatchObject({latitude:previous.latitude,address:'Cell area (approx.): New'});
 expect(mergeDashboardTelemetry(previous,{gpsValid:true,latitude:29}).address).toBe(previous.address);
});
