import {useEffect,useRef,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Maximize2,Minimize2,Plus,Search} from 'lucide-react';
import type {Geofence,GeofenceInput} from '../../../../packages/shared-types/src/geofences';
import {api,errorMessage} from '../services/api/client';
import type {Envelope} from '../types';
import {DataTable,type Column} from '../components/ui/DataTable';
import {SearchableSelect} from '../components/ui/SearchableSelect';
import {StatePanel} from '../components/ui/StatePanel';
import {dateTime} from '../lib/format';
import {GeofenceMap} from '../features/geofences/GeofenceMap';
import {GeofenceCategoryBadge,GeofenceCategorySelect} from '../features/geofences/GeofenceCategory';
import '../features/geofences/geofences.css';

type Vehicle={id:string;vehicle_number:string};
type Drawing=Pick<GeofenceInput,'geometry'|'shapeType'|'radiusMeters'>;
function useDebounced(value:string){const [result,setResult]=useState(value);useEffect(()=>{const timer=setTimeout(()=>setResult(value),300);return()=>clearTimeout(timer)},[value]);return result}
function VehicleSelector({selected,onChange,disabled}:{selected:Vehicle[];onChange:(vehicles:Vehicle[])=>void;disabled:boolean}){
 const [search,setSearch]=useState(''),[page,setPage]=useState(1),[open,setOpen]=useState(false),[issue,setIssue]=useState(''),[selecting,setSelecting]=useState(false);const debounced=useDebounced(search),bulkRequest=useRef<AbortController|null>(null);
 useEffect(()=>()=>bulkRequest.current?.abort(),[]);
 useEffect(()=>setPage(1),[debounced]);
 const query=useQuery({queryKey:['geofence-vehicles',debounced,page],enabled:open,queryFn:async({signal})=>(await api.get<Envelope<Vehicle[]>>('/geofences/vehicle-options',{params:{search:debounced,page,pageSize:50},signal})).data});
 const add=(vehicles:Vehicle[])=>{const next=[...new Map([...selected,...vehicles].map(v=>[v.id,v])).values()];if(next.length>1000){setIssue('A geofence supports up to 1,000 selected vehicles.');return}setIssue('');onChange(next)};
 const selectAll=async()=>{
  if(selecting)return;
  const controller=new AbortController();bulkRequest.current=controller;setSelecting(true);setIssue('');
  try{
   const all:Vehicle[]=[];
   for(let current=1;current<=10;current++){
    const result=(await api.get<Envelope<Vehicle[]>>('/geofences/vehicle-options',{params:{search:debounced,page:current,pageSize:100},signal:controller.signal})).data;
    if((result.pagination?.total??0)>1000){setIssue('More than 1,000 vehicles match. Narrow the search before selecting all.');return}
    all.push(...result.data);
    if(current*100>=(result.pagination?.total??0))break;
   }
   add(all);
  }catch(error){if(!controller.signal.aborted)setIssue(errorMessage(error))}finally{if(!controller.signal.aborted)setSelecting(false);bulkRequest.current=null}
 };
 return <div className="geofence-vehicle-picker"><SearchableSelect aria-label="Select vehicles" isMulti isDisabled={disabled||selecting} value={selected.map(vehicle=>vehicle.id)} onChange={ids=>{const known=[...selected,...(query.data?.data??[])];onChange(ids.map(id=>known.find(vehicle=>vehicle.id===id)!).filter(Boolean))}} placeholder="Select vehicles" renderMultiValue={ids=>`${ids.length} vehicle${ids.length===1?'':'s'} selected`} options={(query.data?.data??[]).map(vehicle=>({value:vehicle.id,label:vehicle.vehicle_number}))} isLoading={query.isLoading} filterOptions={false} onSearchChange={setSearch} onOpenChange={setOpen} renderMenuFooter={close=><>{query.isError&&<StatePanel kind="error" title="Vehicles unavailable" onRetry={()=>query.refetch()}/>}<div className="geofence-picker-actions"><button type="button" disabled={disabled||selecting||!query.data?.data.length} onClick={()=>void selectAll()}>{selecting?'Selecting…':'Select all results'}</button><button type="button" disabled={disabled||selecting} onClick={()=>onChange([])}>Deselect all</button><button type="button" onClick={close}>Done</button></div>{issue&&<p role="alert">{issue}</p>}<div className="geofence-picker-actions"><button type="button" disabled={page===1||disabled} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button type="button" disabled={disabled||page*50>=(query.data?.pagination?.total??0)} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}/>{selected.length>0&&<small title={selected.map(v=>v.vehicle_number).join(', ')}>{selected.slice(0,3).map(v=>v.vehicle_number).join(', ')}{selected.length>3?` +${selected.length-3}`:''}</small>}</div>;
}
export function GeofencePage(){
 const cache=useQueryClient();
 const [search,setSearch]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<Geofence|null>(null),[editing,setEditing]=useState(false),[editId,setEditId]=useState<string|null>(null),[name,setName]=useState(''),[category,setCategory]=useState(''),[vehicles,setVehicles]=useState<Vehicle[]>([]),[draft,setDraft]=useState<Drawing|null>(null),[message,setMessage]=useState(''),[formError,setFormError]=useState(''),[session,setSession]=useState(0),[tableFullscreen,setTableFullscreen]=useState(false);
 const busy=useRef(false),debounced=useDebounced(search);
 useEffect(()=>setPage(1),[debounced]);
 useEffect(()=>{if(!editing)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[editing]);
 useEffect(()=>{if(!editing)return;const warn=(event:MouseEvent)=>{const link=(event.target as HTMLElement).closest('a[href]');if(link&&!window.confirm('Leave this page and discard unsaved geofence changes?')){event.preventDefault();event.stopPropagation()}};document.addEventListener('click',warn,true);return()=>document.removeEventListener('click',warn,true)},[editing]);
 const query=useQuery({queryKey:['geofences',debounced,page],queryFn:async({signal})=>(await api.get<Envelope<Geofence[]>>('/geofences',{params:{search:debounced,page,pageSize:25},signal})).data});
 const reset=()=>{setName('');setCategory('');setVehicles([]);setDraft(null);setFormError('');setSession(s=>s+1)};
 const open=(f:Geofence|null)=>{if(editing&&!window.confirm('Discard the current unsaved changes?'))return;reset();setEditId(f?.id??null);setSelected(f);if(f){setName(f.name);setCategory(f.categoryKey);setVehicles(f.vehicles);setDraft({geometry:f.geometry,shapeType:f.shapeType,radiusMeters:f.radiusMeters})}setEditing(true);setMessage('')};
 const save=useMutation({mutationFn:async(input:GeofenceInput)=>(await (editId?api.patch<Envelope<Geofence>>(`/geofences/${editId}`,input):api.post<Envelope<Geofence>>('/geofences',input))).data.data,onSuccess:f=>{setSelected(f);setEditing(false);setMessage(editId?'Geofence updated.':'Geofence created.');setPage(1);void cache.invalidateQueries({queryKey:['geofences']})},onError:e=>setFormError(errorMessage(e)),onSettled:()=>{busy.current=false}});
 const remove=useMutation({mutationFn:(id:string)=>api.delete(`/geofences/${id}`),onSuccess:()=>{setSelected(null);setPage(1);setMessage('Geofence deleted.');void cache.invalidateQueries({queryKey:['geofences']})}});
 const submit=()=>{if(busy.current)return;if(!name.trim()||!category||!vehicles.length||!draft){setFormError('Enter a name, choose a category and vehicles, and finish drawing a boundary.');return}busy.current=true;setFormError('');save.mutate({name:name.trim(),categoryKey:category,vehicleIds:vehicles.map(v=>v.id),...draft})};
 const columns:Column<Geofence>[]=[{key:'sn',label:'SN',render:(_,i)=>(page-1)*25+i+1},{key:'name',label:'Name',render:f=><strong>{f.name}</strong>},{key:'category',label:'Category',render:f=><GeofenceCategoryBadge categoryKey={f.categoryKey}/>},{key:'shape',label:'Type',render:f=>f.shapeType},{key:'assignment',label:'Assign Type',render:()=>'VEHICLE'},{key:'vehicles',label:'Assign To',render:f=><span title={f.vehicles.map(v=>v.vehicle_number).join(', ')}>{f.vehicles.slice(0,2).map(v=>v.vehicle_number).join(', ')}{f.vehicles.length>2?` +${f.vehicles.length-2}`:''}</span>},{key:'created',label:'Created At',render:f=>dateTime(f.created_at)},{key:'updated',label:'Last Updated',render:f=>dateTime(f.updated_at)},{key:'actions',label:'Actions',render:f=><div className="geofence-row-actions"><button disabled={save.isPending||remove.isPending} onClick={e=>{e.stopPropagation();open(f)}}>Edit</button><button disabled={editing||remove.isPending} onClick={e=>{e.stopPropagation();if(window.confirm(`Delete geofence “${f.name}”?`))remove.mutate(f.id)}}>Delete</button></div>}];
 const total=query.data?.pagination?.total??0;
 return <section className="page geofence-page"><div className="page-heading"><div><p className="eyebrow">Fleet boundaries</p><h1>Geofence management</h1></div><button className="button" disabled={save.isPending} onClick={()=>open(null)}><Plus/>Add geofence</button></div>{message&&<div className="geofence-success" role="status">{message}</div>}{remove.isError&&<div className="inline-error" role="alert">{errorMessage(remove.error)}</div>}
 {editing&&<form className="geofence-form" onSubmit={e=>{e.preventDefault();submit()}}><fieldset disabled={save.isPending}><legend>{editId?'Edit geofence':'New geofence'}</legend><div className="geofence-form-grid"><label>Name *<input required maxLength={120} value={name} placeholder="Geofence name" onChange={e=>setName(e.target.value)}/></label><label>Category *<GeofenceCategorySelect value={category} onChange={setCategory} disabled={save.isPending}/></label><label>Assign Type<input readOnly value="VEHICLE"/></label><div><span className="geofence-field-label">Assign To *</span><VehicleSelector selected={vehicles} onChange={setVehicles} disabled={save.isPending}/></div></div>{draft?.shapeType==='CIRCLE'&&<label className="geofence-radius">Radius (meters)<input type="number" min="0.01" max="1000000" step="any" required value={draft.radiusMeters??''} onChange={e=>setDraft({...draft,radiusMeters:Number(e.target.value)})}/></label>}{formError&&<div className="inline-error" role="alert">{formError}</div>}<div className="geofence-form-actions"><button type="button" className="secondary-button" onClick={()=>{if(window.confirm('Close and discard unsaved changes?')){setEditing(false);reset()}}}>Close</button><button type="button" className="secondary-button" onClick={()=>{if(window.confirm('Clear all unsaved form fields and drawing?'))reset()}}>Clear</button><button className="button" type="submit" disabled={save.isPending||!draft}>{save.isPending?'Saving…':'Save'}</button></div></fieldset></form>}
 <div className={`geofence-workspace ${tableFullscreen?'table-fullscreen':''}`}><div className="admin-panel geofence-list"><div className="panel-toolbar"><label className="search-box"><Search/><input aria-label="Search geofences" placeholder="Search name, category or vehicle" value={search} maxLength={100} onChange={e=>setSearch(e.target.value)}/></label><div className="toolbar-actions"><button className={`secondary-button geofence-table-fullscreen ${tableFullscreen?'active':''}`} type="button" title={tableFullscreen?'Exit Table Fullscreen':'Table Fullscreen'} aria-label={tableFullscreen?'Exit Table Fullscreen':'Table Fullscreen'} aria-pressed={tableFullscreen} onClick={()=>setTableFullscreen(value=>!value)}>{tableFullscreen?<Minimize2/>:<Maximize2/>}</button><button className="secondary-button" disabled title="Geofence PDF export is not available">PDF</button><button className="secondary-button" disabled title="Geofence Excel export is not available">Excel</button></div></div>{query.isLoading?<StatePanel kind="loading" title="Loading geofences"/>:query.isError?<StatePanel kind="error" title="Geofences unavailable" detail={errorMessage(query.error)} onRetry={()=>query.refetch()}/>:!query.data?.data.length?<StatePanel kind="empty" title="No geofences found" detail={debounced?'Try a different search.':'Add a geofence and assign it to your vehicles.'}/>:<DataTable columns={columns} rows={query.data.data} selected={selected?.id} onSelect={f=>{if(!editing)setSelected(f)}}/>}<div className="pagination"><span>Showing {total?Math.min((page-1)*25+1,total):0} to {Math.min(page*25,total)} of {total} entries</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={page*25>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div><div className="geofence-map-panel" hidden={tableFullscreen} aria-hidden={tableFullscreen}><GeofenceMap rows={query.data?.data??[]} selected={selected} onSelect={setSelected} draft={draft} editing={editing} disabled={save.isPending} onChange={setDraft} session={session}/></div></div></section>;
}
