import '@testing-library/jest-dom/vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {VehiclePage} from './VehiclePage';
const mocks=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn(),role:'ADMIN'}));
vi.mock('../services/api/client',()=>({api:mocks,errorMessage:()=> 'API error'}));
vi.mock('../lib/auth',()=>({claims:()=>({id:'actor',role:mocks.role})}));
const row={id:'vehicle-1',vehicle_number:'TEST-001',vehicle_type:'Truck',mileage:100,overspeed_limit:80,owner_id:'client-1',coins:1,billing_start:null,billing_due:null,alias:'Test',remark:null,active:true,auto_renewal:false,door_configured:false,relay_configured:false,buzzer_configured:false,ignition_wiring:'UNKNOWN',ac_power_plus:false,parking_alarm_on_ignition:false,created_at:'2026-01-01',updated_at:'2026-01-01',client_name:'Client A',client_email:'client@test.local',client_username:'client.a',admin_id:'admin-1',admin_name:'Admin A',admin_email:'admin@test.local',admin_username:'admin.a',device_id:'device-1',imei:'123456789',protocol:'GT06',device_model:null,sim_number:null,sim_operator:null,sim_type:null,capabilities:{door:'SUPPORTED'},last_seen_at:null,speed:null,tracker_timestamp:null,server_received_at:null,fleet_status:'NEW'};
const counts={ALL:1,OVERSPEED:0,RUNNING:0,IDLE:0,STOPPED:0,UNREACHABLE:0,NEW:1,INACTIVE:0};
const renderPage=()=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><VehiclePage/></QueryClientProvider>);
beforeEach(()=>{vi.clearAllMocks();mocks.role='ADMIN';mocks.delete.mockResolvedValue({data:{success:true}});mocks.get.mockImplementation((url:string)=>url==='/fleet-vehicles'?Promise.resolve({data:{data:[row],counts,pagination:{page:1,pageSize:25,total:1}}}):Promise.resolve({data:{data:[]}}))});afterEach(cleanup);
it('renders vehicles without count or upload controls and reveals Edit vehicle only after checkbox selection',async()=>{renderPage();expect(await screen.findByText('TEST-001')).toBeInTheDocument();expect(screen.queryByText('1 vehicles')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Upload Vehicle/i})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Edit vehicle/i})).not.toBeInTheDocument();fireEvent.click(screen.getByLabelText('Select TEST-001'));expect(screen.getByRole('button',{name:/Edit vehicle/i})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/New/}));await waitFor(()=>expect(mocks.get).toHaveBeenCalledWith('/fleet-vehicles',expect.objectContaining({params:expect.objectContaining({status:'NEW'})}))) });
it('shows empty and error states without demo fallback',async()=>{mocks.get.mockImplementation((url:string)=>url==='/fleet-vehicles'?Promise.resolve({data:{data:[],counts:{...counts,ALL:0,NEW:0},pagination:{page:1,pageSize:25,total:0}}}):Promise.resolve({data:{data:[]}}));const view=renderPage();expect(await screen.findByText('No vehicles found')).toBeInTheDocument();view.unmount();cleanup();mocks.get.mockImplementation((url:string)=>url==='/fleet-vehicles'?Promise.reject(new Error('offline')):Promise.resolve({data:{data:[]}}));renderPage();expect(await screen.findByText('Vehicle list unavailable')).toBeInTheDocument()});
it('shows clients only the reduced operational columns and no management actions',async()=>{mocks.role='CLIENT';renderPage();expect(await screen.findByText('TEST-001')).toBeInTheDocument();for(const heading of ['Vehicle Number','Vehicle Type','Status','Speed','Last GPS','Since','TodayKm','TodayDu','Overspeed'])expect(screen.getByRole('columnheader',{name:new RegExp(heading)})).toBeVisible();expect(screen.queryByRole('columnheader',{name:'IMEI'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Add Vehicle/i})).not.toBeInTheDocument();expect(screen.queryByLabelText('Select TEST-001')).not.toBeInTheDocument();expect(mocks.get).not.toHaveBeenCalledWith('/client-options')});

it('shows the owning admin beside the client and opens editing directly for the super-admin',async()=>{
 mocks.role='SUPER_ADMIN';renderPage();await screen.findByText('TEST-001');
 expect(screen.getByRole('columnheader',{name:/^Admin/})).toBeVisible();
 expect(screen.getByText('Admin A')).toBeVisible();
 const headers=screen.getAllByRole('columnheader').map(header=>header.textContent);
 expect(headers.findIndex(text=>text?.startsWith('Admin'))).toBe(headers.findIndex(text=>text?.startsWith('Client'))-1);
 expect(screen.getByLabelText('Select TEST-001')).not.toBeChecked();
 fireEvent.click(screen.getByRole('button',{name:'Edit TEST-001'}));
 expect(screen.getByRole('dialog')).toHaveTextContent('Edit Vehicle');
 expect(screen.getByLabelText('Vehicle Number')).toHaveValue('TEST-001');
 expect(screen.getByLabelText('Vehicle Number')).not.toBeDisabled();
 expect(screen.getByRole('combobox',{name:'Vehicle Type'})).not.toBeDisabled();
 expect(screen.getByRole('combobox',{name:'Client'})).not.toBeDisabled();
 expect(screen.getByRole('button',{name:'Save changes'})).toBeVisible();
});
