import React from 'react';
import {act,create,type ReactTestRenderer} from 'react-test-renderer';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {expect,it,vi} from 'vitest';
import EditVehicle from '../app/(app)/edit-vehicle';
const state=vi.hoisted(()=>({patch:vi.fn(),replace:vi.fn(),vehicle:{id:'vehicle-1',vehicle_number:'TEST-001',vehicle_type:'Scooty',mileage:30,odometer:0,overspeed_limit:90,alias:'Test Bike',remark:'',gps_location:'Under seat'}}));
vi.mock('../services/api/client',()=>({api:{patch:state.patch}}));
vi.mock('../services/api/mobile',()=>({getEditableVehicle:async()=>state.vehicle,requireOnline:()=>{},mobileMessage:(error:Error)=>error.message}));
vi.mock('expo-router',()=>({useLocalSearchParams:()=>({vehicleId:'vehicle-1'}),router:{replace:state.replace}}));
vi.mock('../components/StateViews',()=>({Loading:'Loading',ErrorState:'ErrorState'}));
vi.mock('react-native',()=>({Text:'Text'}));
vi.mock('../components/MobileForm',()=>({Access:({children}:{children:React.ReactNode})=><>{children}</>,Screen:({children}:{children:React.ReactNode})=><>{children}</>,Field:'Field',Options:'Options',Button:'Button',form:{error:{}}}));
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
it('loads all editable fields, rejects invalid mileage and saves GPS installation location with the vehicle',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});state.patch.mockResolvedValue({data:{}});
 let tree!:ReactTestRenderer;
 await act(async()=>{tree=create(<QueryClientProvider client={cache}><EditVehicle/></QueryClientProvider>)});
 await act(async()=>{await new Promise(resolve=>setTimeout(resolve,10))});
 expect(tree.root.findByProps({label:'Odometer'}).props.value).toBe('0');
 await act(async()=>tree.root.findByProps({label:'Mileage'}).props.onChangeText('-1'));
 await act(async()=>{tree.root.findByProps({label:'Save'}).props.onPress();await Promise.resolve()});
 expect(state.patch).not.toHaveBeenCalled();
 expect(JSON.stringify(tree.toJSON())).toContain('Mileage must be');
 await act(async()=>{tree.root.findByProps({label:'Mileage'}).props.onChangeText('40');tree.root.findByProps({label:'GPS Location'}).props.onChangeText('Upper dashboard')});
 await act(async()=>{tree.root.findByProps({label:'Save'}).props.onPress();await Promise.resolve()});
 expect(state.patch).toHaveBeenCalledWith('/mobile/vehicles/vehicle-1',{vehicleNumber:'TEST-001',vehicleType:'Scooty',mileage:40,odometer:0,overspeedLimit:90,alias:'Test Bike',remark:'',gpsLocation:'Upper dashboard'});
 expect(state.replace).toHaveBeenCalledWith('/(app)/vehicles');
 await act(async()=>tree.unmount());cache.clear();
});
