import type {ProtocolDecoder}from '@fleet/protocol-types';import type {DecodedMessage,NormalizedLocation}from '@fleet/shared-types';import {ack}from './acknowledgements.js';import {bcdImei,gt06Coordinate,parseDate,validGt06Frame}from './parser.js';
export class Gt06Decoder implements ProtocolDecoder{readonly protocol='GT06';matches(frame:Buffer){return frame.length>=10&&frame[0]===0x78&&frame[1]===0x78&&[0x01,0x12,0x13,0x16,0x22].includes(frame[3])}decode(frame:Buffer,receivedAt:Date):DecodedMessage{if(!validGt06Frame(frame))throw new Error('Invalid GT06 frame');const type=frame[3],body=frame.subarray(4,frame.length-6),serial=frame.readUInt16BE(frame.length-6);if(type===0x01)return{type:'login',imei:bcdImei(body.subarray(0,8)),acknowledgement:ack(type,serial)};if(type===0x13){if(body.length<5)throw new Error('Truncated GT06 heartbeat');const terminalInfo=body[0];return{type:'heartbeat',acknowledgement:ack(type,serial),metadata:{terminalInfo,ignition:(terminalInfo&0x02)!==0,gpsPositioned:(terminalInfo&0x40)!==0,charging:(terminalInfo&0x04)!==0,defense:(terminalInfo&0x01)!==0,oilElectricityConnected:(terminalInfo&0x80)===0,voltageLevel:body[1],gsmSignal:body[2]}}}if((type!==0x12&&type!==0x22&&type!==0x16)||body.length<18||(type===0x16&&body.length<32))throw new Error('Invalid GT06 location');const courseStatus=body.readUInt16BE(16);const location:NormalizedLocation={deviceId:null,vehicleId:null,imei:'',protocol:this.protocol,trackerTimestamp:parseDate(body.subarray(0,6)),serverReceivedAt:receivedAt,latitude:gt06Coordinate(body.readUInt32BE(7))*(courseStatus&0x0400?1:-1),longitude:gt06Coordinate(body.readUInt32BE(11))*(courseStatus&0x0800?-1:1),speed:body[15],course:courseStatus&0x03ff,ignition:type===0x16?(body[27]&0x02)!==0:null,satellites:body[6]&0x0f,gpsValid:(courseStatus&0x1000)!==0,batteryPercent:null,batteryVoltage:null,gsmSignal:null,odometer:null,ac:null,door:null,relay:null,metadata:cellMetadata(body,type)};return{type:'location',location,acknowledgement:ack(type,serial)}}}

// GT06 v1.8.1 sections 5.2/5.3: 0x12 carries eight LBS bytes;
// 0x16 prefixes those bytes with an LBS-length byte. 0x22 is a variant
// without a verified LBS layout here, so do not interpret its extension.
function cellMetadata(body:Buffer,type:number):Record<string,unknown> {
 const offset=type===0x12?18:type===0x16&&body[18]===9?19:null;
 if(offset===null||body.length<offset+8)return {};
 return {cell:{mcc:body.readUInt16BE(offset),mnc:body[offset+2],lac:body.readUInt16BE(offset+3),cellId:body.readUIntBE(offset+5,3)}};
}
