import {useState} from 'react';
import {NavLink,Outlet,useLocation} from 'react-router-dom';
import {Activity,BarChart3,ChevronDown,Contact,Home,LogOut,Menu,PanelLeftClose,ShieldCheck,Truck,Users,Wifi} from 'lucide-react';
import riLogo from '../../../mobile/assets/loginlogo.png';
import {claims,setTokens} from '../lib/auth';
import './AppShell.css';
const future=['User & Group','Alert','Geofence','Mgmt'];
const vehicleReports=[['Status Report','/reports/status'],['Idle Report','/reports/idle'],['Running Report','/reports/running'],['Stoppage Report','/reports/stoppage'],['Overspeed Report','/reports/overspeed'],['Unreachable Report','/reports/unreachable']] as const;
export function AppShell(){
 const location=useLocation(),onReports=location.pathname.startsWith('/reports/');
 const [open,setOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[dashboardOpen,setDashboardOpen]=useState(!onReports),[reportsOpen,setReportsOpen]=useState(onReports),[vehicleReportsOpen,setVehicleReportsOpen]=useState(vehicleReports.some(([,path])=>path===location.pathname));
 const role=claims()?.role,close=()=>setOpen(false);
 return <div className={`app-frame ${collapsed?'sidebar-collapsed':''}`}>
  <header className="topbar"><div className="brand"><img className="brand-logo" src={riLogo} alt="RI logo"/><strong>RI</strong></div><button className="icon-button desktop-collapse" onClick={()=>setCollapsed(value=>!value)} aria-label="Toggle sidebar"><PanelLeftClose/></button><button className="icon-button mobile-menu" onClick={()=>setOpen(value=>!value)} aria-label="Open navigation"><Menu/></button><nav className="top-links"><NavLink to="/dashboard"><Home/>Home</NavLink><span className="flex items-center gap-2 px-3 py-2 text-sm text-slate-200" title="Contact details are not configured"><Contact/>Contact</span></nav><div className="top-actions"><span className="live-indicator"><Wifi/>Live</span><button className="icon-button" onClick={()=>setTokens(null)} aria-label="Sign out"><LogOut/></button></div></header>
  <aside className={`sidebar ${open?'open':''}`}><div className="profile"><div className="avatar">RI</div><div><strong>RI Operator</strong><span>{role?.replace('_',' ')}</span></div></div><div className="nav-label">Workspace</div><nav className="side-nav">
   <button type="button" className="nav-group-title" onClick={()=>setDashboardOpen(value=>!value)} aria-expanded={dashboardOpen}><Activity/><span>Dashboard</span><ChevronDown className={dashboardOpen?'nav-chevron open':'nav-chevron'}/></button>{dashboardOpen&&<div className="nav-children"><NavLink to="/dashboard" end onClick={close}><Activity/><span>Dashboard</span></NavLink><NavLink to="/dashboard/playback" onClick={close}><span className="route-dot"/><span>Playback</span></NavLink></div>}
   {(role==='ADMIN'||role==='SUPER_ADMIN')&&<><NavLink to="/vehicles" onClick={close}><Truck/><span>Vehicle</span></NavLink><NavLink to="/admin" onClick={close}><ShieldCheck/><span>Admin</span></NavLink><NavLink to="/clients" onClick={close}><Users/><span>Client</span></NavLink></>}
   <button type="button" className={`nav-group-title ${onReports?'section-active':''}`} onClick={()=>setReportsOpen(value=>!value)} aria-expanded={reportsOpen}><BarChart3/><span>Reports</span><ChevronDown className={reportsOpen?'nav-chevron open':'nav-chevron'}/></button>{reportsOpen&&<div className="nav-children report-links"><NavLink to="/reports/distance" onClick={close}><span className="route-dot"/><span>Distance Report</span></NavLink><NavLink to="/reports/ac" onClick={close}><span className="route-dot"/><span>AC Report</span></NavLink><NavLink to="/reports/packet" onClick={close}><span className="route-dot"/><span>Packet Report</span></NavLink><NavLink to="/reports/travel-summary" onClick={close}><span className="route-dot"/><span>Travel Summary</span></NavLink><NavLink to="/reports/daily-trip-summary" onClick={close}><span className="route-dot"/><span>Daily Trip Summary</span></NavLink><button type="button" className={`nav-subgroup ${vehicleReportsOpen?'section-active':''}`} onClick={()=>setVehicleReportsOpen(value=>!value)}><span className="route-dot"/><span>Vehicle Reports</span><ChevronDown className={vehicleReportsOpen?'nav-chevron open':'nav-chevron'}/></button>{vehicleReportsOpen&&<div className="deferred-reports vehicle-report-links">{vehicleReports.map(([label,path])=><NavLink key={path} to={path} onClick={close}><span className="route-dot"/><span>{label}</span></NavLink>)}</div>}</div>}
   <div className="nav-label later">Coming later</div>{future.map(item=><span className="future-link" key={item}>{item}</span>)}
  </nav></aside>{open&&<button className="sidebar-scrim" onClick={close} aria-label="Close navigation"/>}<main className="main-content"><Outlet/></main>
 </div>
}
