import {useEffect,useState} from 'react';
import {NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {Bell,ChevronDown,Contact,Database,Expand,Grid2X2,Home,LogOut,Menu,PanelLeftClose,Shrink,X} from 'lucide-react';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faBell,faCar,faChartPie,faCircleDot,faDrawPolygon,faGaugeHigh,faUsersGear,faUserTie} from '@fortawesome/free-solid-svg-icons';
import {faCircle} from '@fortawesome/free-regular-svg-icons';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {io} from 'socket.io-client';
import {api} from '../services/api/client';import type {AccountSummary,Envelope} from '../types';
import riLogo from '../../../mobile/assets/loginlogo.png';
import {claims,getTokens,setTokens} from '../lib/auth';
import './AppShell.css';
import '../features/alerts/alerts.css';
import {PageFilterContext} from '../features/shell/pageFilterContext';
import {SidebarProfile} from './SidebarProfile';
const vehicleReports=[['Status Report','/reports/status'],['Idle Report','/reports/idle'],['Running Report','/reports/running'],['Stoppage Report','/reports/stoppage'],['Overspeed Report','/reports/overspeed'],['Unreachable Report','/reports/unreachable']] as const;
const ChildCircle=()=> <FontAwesomeIcon className="sidebar-child-icon" icon={faCircle}/>;
const ReportDot=()=> <FontAwesomeIcon className="sidebar-child-icon" icon={faCircleDot}/>;
export function AppShell(){
 const location=useLocation(),onReports=location.pathname.startsWith('/reports/'),onAlerts=location.pathname.startsWith('/alerts');
 const navigate=useNavigate();
 const [open,setOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[dashboardOpen,setDashboardOpen]=useState(!onReports&&!onAlerts),[reportsOpen,setReportsOpen]=useState(onReports),[vehicleReportsOpen,setVehicleReportsOpen]=useState(vehicleReports.some(([,path])=>path===location.pathname)),[alertsOpen,setAlertsOpen]=useState(onAlerts);const queryCache=useQueryClient();
 const [filterOpen,setFilterOpen]=useState(false),[fullscreen,setFullscreen]=useState(false),[coinsOpen,setCoinsOpen]=useState(false);
 const [dismissed,setDismissed]=useState<string[]>([]);const announcements=useQuery({queryKey:['active-announcements'],queryFn:async()=>(await api.get<Envelope<Array<{id:string;title:string;bodyHtml:string;messageType?:'TEXT'|'IMAGE';imageUrl?:string|null;dontShowAgain:boolean}>>>('/announcements/current')).data.data,staleTime:60000});const dismiss=useMutation({mutationFn:(id:string)=>api.post(`/announcements/${id}/dismiss`),onSuccess:()=>void queryCache.invalidateQueries({queryKey:['active-announcements']})});
 const userId=claims()?.id;
 const account=useQuery({queryKey:['account-summary',userId],enabled:!!userId,queryFn:async()=>(await api.get<Envelope<AccountSummary>>('/account-summary')).data.data,staleTime:10000,refetchInterval:10000});
 const [liveNotification,setLiveNotification]=useState<{id:string;message:string}|null>(null);useEffect(()=>{const token=getTokens()?.accessToken;if(!token)return;const base=(import.meta.env.VITE_SOCKET_URL||import.meta.env.VITE_API_URL||'http://localhost:3000').replace(/\/api\/v1\/?$/,'');const socket=io(base,{auth:{token},transports:['websocket']});socket.on('notification:new',(payload:{id?:string;message?:string})=>{if(payload.id&&payload.message)setLiveNotification({id:payload.id,message:payload.message})});return()=>{socket.disconnect()}},[]);
 const role=claims()?.role,close=()=>setOpen(false);
 useEffect(()=>{setFilterOpen(['/reports/coin-distribution','/reports/distance','/reports/ac','/reports/packet','/reports/travel-summary','/reports/daily-trip-summary','/reports/status','/reports/idle','/reports/running','/reports/stoppage','/reports/overspeed','/reports/unreachable'].includes(location.pathname));setCoinsOpen(false)},[location.pathname]);
 useEffect(()=>{const update=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update)},[]);
 const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{/* Fullscreen can be denied by browser policy. */}};
 const signOut=()=>{setTokens(null);queryCache.clear();navigate('/login',{replace:true})};
 const filterController={open:filterOpen,setOpen:setFilterOpen,toggle:()=>setFilterOpen(value=>!value),close:()=>setFilterOpen(false)};
 return <PageFilterContext.Provider value={filterController}><div className={`app-frame ${collapsed?'sidebar-collapsed':''} ${filterOpen?'page-filter-visible':''}`}>
  <header className="topbar"><div className="brand"><img className="brand-logo" src={riLogo} alt="RI logo"/><strong>RI</strong></div><button className="icon-button desktop-collapse" onClick={()=>setCollapsed(value=>!value)} aria-label="Toggle sidebar"><PanelLeftClose/></button><button className="icon-button mobile-menu" onClick={()=>setOpen(value=>!value)} aria-label="Open navigation"><Menu/></button><nav className="top-links"><NavLink to="/dashboard"><Home/>Home</NavLink><span className="flex items-center gap-2 px-3 py-2 text-sm text-slate-200" title="Contact details are not configured"><Contact/>Contact</span></nav><div className="top-actions">
   <button className="header-tool" onClick={()=>setCoinsOpen(value=>!value)} aria-label="Coins" aria-expanded={coinsOpen} title="Coins"><Database/></button>
   <button className="header-tool" onClick={toggleFullscreen} aria-label={fullscreen?'Exit fullscreen':'Enter fullscreen'} title={fullscreen?'Exit fullscreen':'Fullscreen'}>{fullscreen?<Shrink/>:<Expand/>}</button>
   <button className="header-tool" onClick={signOut} aria-label="Sign out" title="Sign out"><LogOut/></button>
   <button className={`header-tool ${filterOpen?'active':''}`} onClick={filterController.toggle} aria-label="Page filters" aria-pressed={filterOpen} title="Page filters"><Grid2X2/></button>
   {coinsOpen&&<div className="coin-popover" role="status"><span>Coin balance</span><strong>{account.data?Number(account.data.coins).toLocaleString():'—'}</strong><small>{account.data?.name||account.data?.email||'Loading account…'}</small></div>}
  </div></header>
  <aside className={`sidebar ${open?'open':''}`}><SidebarProfile account={account.data} userId={userId} role={role}/><div className="nav-label">Workspace</div><nav className="side-nav">
   <button type="button" className="nav-group-title" onClick={()=>setDashboardOpen(value=>!value)} aria-expanded={dashboardOpen}><FontAwesomeIcon className="sidebar-fa-icon" icon={faGaugeHigh}/><span>Dashboard</span><ChevronDown className={dashboardOpen?'nav-chevron open':'nav-chevron'}/></button>{dashboardOpen&&<div className="nav-children"><NavLink to="/dashboard" end onClick={close}><ChildCircle/><span>Dashboard</span></NavLink><NavLink to="/dashboard/playback" onClick={close}><ChildCircle/><span>Playback</span></NavLink></div>}
   {(role==='CLIENT'||role==='ADMIN'||role==='SUPER_ADMIN')&&<NavLink to="/vehicles" onClick={close}><FontAwesomeIcon className="sidebar-fa-icon" icon={faCar}/><span>Vehicle</span></NavLink>}{(role==='ADMIN'||role==='SUPER_ADMIN')&&<><NavLink to="/admin" onClick={close}><FontAwesomeIcon className="sidebar-fa-icon" icon={faUsersGear}/><span>Admin</span></NavLink><NavLink to="/clients" onClick={close}><FontAwesomeIcon className="sidebar-fa-icon" icon={faUserTie}/><span>Client</span></NavLink></>}
   <button type="button" className={`nav-group-title ${onReports?'section-active':''}`} onClick={()=>setReportsOpen(value=>!value)} aria-expanded={reportsOpen}><FontAwesomeIcon className="sidebar-fa-icon" icon={faChartPie}/><span>Reports</span><ChevronDown className={reportsOpen?'nav-chevron open':'nav-chevron'}/></button>{reportsOpen&&<div className="nav-children report-links">{(role==='ADMIN'||role==='SUPER_ADMIN')&&<NavLink to="/reports/coin-distribution" onClick={close}><ReportDot/><span>Coin Distribution</span></NavLink>}<NavLink to="/reports/distance" onClick={close}><ReportDot/><span>Distance Report</span></NavLink><NavLink to="/reports/ac" onClick={close}><ReportDot/><span>AC Report</span></NavLink><NavLink to="/reports/packet" onClick={close}><ReportDot/><span>Packet Report</span></NavLink><NavLink to="/reports/travel-summary" onClick={close}><ReportDot/><span>Travel Summary</span></NavLink><NavLink to="/reports/daily-trip-summary" onClick={close}><ReportDot/><span>Daily Trip Summary</span></NavLink><button type="button" className={`nav-subgroup ${vehicleReportsOpen?'section-active':''}`} onClick={()=>setVehicleReportsOpen(value=>!value)}><ReportDot/><span>Vehicle Reports</span><ChevronDown className={vehicleReportsOpen?'nav-chevron open':'nav-chevron'}/></button>{vehicleReportsOpen&&<div className="deferred-reports vehicle-report-links">{vehicleReports.map(([label,path])=><NavLink key={path} to={path} onClick={close}><ChildCircle/><span>{label}</span></NavLink>)}</div>}</div>}
   <button type="button" className={`nav-group-title ${onAlerts?'section-active':''}`} onClick={()=>setAlertsOpen(value=>!value)} aria-expanded={alertsOpen}><FontAwesomeIcon className="sidebar-fa-icon" icon={faBell}/><span>Alert</span><ChevronDown className={alertsOpen?'nav-chevron open':'nav-chevron'}/></button>{alertsOpen&&<div className="nav-children"><NavLink to="/alerts" end onClick={close}><ChildCircle/><span>Configure Alert</span></NavLink><NavLink to="/alerts/notifications" onClick={close}><ChildCircle/><span>Notifications History</span></NavLink><NavLink to="/alerts/announcements" onClick={close}><ChildCircle/><span>Announcement</span></NavLink></div>}
   {role==='SUPER_ADMIN'&&<NavLink to="/admin/device-lookup" onClick={close}><Database/><span>GPS / SIM Lookup</span></NavLink>}{(role==='SUPER_ADMIN'||(role==='ADMIN'&&account.data?.can_view_packet_health))&&<NavLink to="/admin/packet-health" onClick={close}><Database/><span>Packet Health</span></NavLink>}
   <NavLink to="/geofences" onClick={close}><FontAwesomeIcon className="sidebar-fa-icon" icon={faDrawPolygon}/><span>Geofence</span></NavLink>
  </nav></aside>{open&&<button className="sidebar-scrim" onClick={close} aria-label="Close navigation"/>}<main className="main-content">{liveNotification&&<aside className="live-alert-toast" role="status"><Bell/><span>{liveNotification.message}</span><button aria-label="Dismiss notification" onClick={()=>setLiveNotification(null)}><X/></button></aside>}{announcements.data?.filter(item=>!dismissed.includes(item.id)).map(item=><aside className="announcement-banner" key={item.id}><div><strong>{item.title}</strong>{item.messageType==='IMAGE'?(item.imageUrl?<img src={item.imageUrl} alt={item.title} onError={event=>{event.currentTarget.replaceWith(document.createTextNode('Image unavailable'))}}/>:<span>Image unavailable</span>):<div dangerouslySetInnerHTML={{__html:item.bodyHtml}}/>}</div><button aria-label="Dismiss announcement" onClick={()=>{setDismissed(ids=>[...ids,item.id]);if(item.dontShowAgain)dismiss.mutate(item.id)}}><X/></button></aside>)}<Outlet/></main>
 </div></PageFilterContext.Provider>
}
