import { useState } from 'react';
import { Modal, Pressable, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { Access, Screen, Field, Options, Check, Button, form } from '../../components/MobileForm';
import { api } from '../../services/api/client';
import { useAccount, mobileMessage, requireOnline } from '../../services/api/mobile';
import { capabilities } from '../../features/account/capabilities';
interface Announcement {id:string;title:string;bodyHtml:string|null;messageType:string;startsAt:string;endsAt:string;active:boolean;dontShowAgain:boolean;clientIds:string[];selectedAdminId:string|null}
const plain=(html:string)=>html.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').trim();
const escape=(value:string)=>value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>');
const localDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const localTime=(date:Date)=>`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;
export default function Announcements(){return <Access capability="announcements"><AnnouncementList/></Access>}
function AnnouncementList(){
 const account=useAccount(),caps=capabilities(account.data);
 const [editing,setEditing]=useState<Announcement|null|undefined>(undefined),[error,setError]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false);
 const q=useQuery({queryKey:['mobile-announcement-management',page],queryFn:async()=>(await api.get<{data:Announcement[];pagination:{total:number}}>('/announcements',{params:{page,pageSize:25}})).data});
 async function archive(id:string){if(busy)return;setBusy(true);try{requireOnline();await api.delete(`/announcements/${id}`);await q.refetch();setError('')}catch(e){setError(mobileMessage(e))}finally{setBusy(false)}}
 return <Screen backTo="profile" title="Announcement">{caps.addAnnouncement?<Button label="Add Announcement" onPress={()=>setEditing(null)}/>:null}{q.isLoading?<Text>Loading announcements…</Text>:null}{q.isError?<Button label="Retry announcements" onPress={()=>void q.refetch()}/>:null}{error?<Text style={form.error}>{error}</Text>:null}{q.data?.data.map(item=><View key={item.id} style={form.card}><Text style={form.heading}>{item.title}</Text><Text>{item.messageType==='TEXT'?plain(item.bodyHtml??''):'Image announcement'}</Text><Text style={form.muted}>{new Date(item.startsAt).toLocaleString()} – {new Date(item.endsAt).toLocaleString()}</Text><Text>{item.active?'Active':'Inactive'}</Text><View style={{flexDirection:'row',gap:20}}>{caps.editAnnouncement&&item.messageType==='TEXT'?<Pressable accessibilityRole="button" onPress={()=>setEditing(item)} style={form.back}><Text>Edit</Text></Pressable>:null}{caps.deleteAnnouncement?<Pressable accessibilityRole="button" disabled={busy} onPress={()=>void archive(item.id)} style={form.back}><Text style={form.error}>Delete</Text></Pressable>:null}</View></View>)}{q.data&&!q.data.data.length?<Text style={form.muted}>No announcements found.</Text>:null}<View style={{flexDirection:'row',justifyContent:'space-between'}}><Button label="Previous" disabled={page===1} onPress={()=>setPage(page-1)}/><Button label="Next" disabled={page*25>=(q.data?.pagination.total??0)} onPress={()=>setPage(page+1)}/></View>
 <Modal visible={editing!==undefined} transparent animationType="fade" onRequestClose={()=>setEditing(undefined)}><View style={{flex:1,backgroundColor:'#0007',justifyContent:'center',padding:16}}><View style={{height:'90%',maxHeight:'95%',width:'100%',maxWidth:520,alignSelf:'center',borderRadius:12,overflow:'hidden',backgroundColor:'#fff'}}>{editing!==undefined?<AnnouncementForm existing={editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);void q.refetch()}}/>:null}</View></View></Modal></Screen>;
}
function AnnouncementForm({existing,onClose,onSaved}:{existing:Announcement|null;onClose():void;onSaved():void}){
 const account=useAccount();const now=new Date();
 const [selectedAdmin,setAdmin]=useState(existing?.selectedAdminId??''),[clients,setClients]=useState<string[]>(existing?.clientIds??[]),[title,setTitle]=useState(existing?.title??''),[body,setBody]=useState(plain(existing?.bodyHtml??''));
 const [from,setFrom]=useState(existing?localDate(new Date(existing.startsAt)):localDate(now)),[fromTime,setFromTime]=useState(existing?localTime(new Date(existing.startsAt)):'00:00'),[to,setTo]=useState(existing?localDate(new Date(existing.endsAt)):localDate(now)),[toTime,setToTime]=useState(existing?localTime(new Date(existing.endsAt)):'23:59');
 const [active,setActive]=useState(existing?.active??true),[dontShowAgain,setDontShowAgain]=useState(existing?.dontShowAgain??false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[clientsOpen,setClientsOpen]=useState(false);
 const adminId=account.data?.role==='ADMIN'?account.data.id:selectedAdmin;
 const admins=useQuery({queryKey:['mobile-announcement-admins'],enabled:account.data?.role==='SUPER_ADMIN',queryFn:async()=>(await api.get<{data:{id:string;label:string}[]}>('/announcements/target-options',{params:{type:'ADMIN'}})).data.data});
 const targets=useQuery({queryKey:['mobile-announcement-clients',adminId],enabled:Boolean(adminId),queryFn:async()=>(await api.get<{data:{id:string;label:string}[]}>('/announcements/target-options',{params:{type:'CLIENT',adminId}})).data.data});
 async function save(){if(busy)return;setBusy(true);setError('');try{requireOnline();if(!adminId||!clients.length||!title.trim()||!body.trim())throw new Error('Select clients and enter a title and body.');if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||!/^\d{2}:\d{2}$/.test(fromTime)||!/^\d{2}:\d{2}$/.test(toTime))throw new Error('Use YYYY-MM-DD dates and HH:mm times.');const startsAt=new Date(`${from}T${fromTime}:00`),endsAt=new Date(`${to}T${toTime}:00`);if(!Number.isFinite(+startsAt)||!Number.isFinite(+endsAt)||endsAt<startsAt)throw new Error('Choose a valid schedule with the end after the start.');const input={targetType:'CLIENT',adminIds:[adminId],clientIds:clients,messageType:'TEXT',title:title.trim(),bodyHtml:escape(body),startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),active,dontShowAgain};if(existing)await api.patch(`/announcements/${existing.id}`,input);else await api.post('/announcements',input);onSaved()}catch(e){setError(mobileMessage(e))}finally{setBusy(false)}}
 return <Screen title={existing?'Edit Announcement':'Add Announcement'} accent onBack={onClose}>{account.data?.role==='SUPER_ADMIN'?<Options label="Admin" options={admins.data??[]} value={selectedAdmin} onChange={id=>{setAdmin(id);setClients([])}}/>:null}<View style={form.card}><Pressable accessibilityRole="button" accessibilityLabel="Select Clients" onPress={()=>setClientsOpen(!clientsOpen)} style={form.select}><Text>{clients.length?`${clients.length} clients selected`:'Select Clients'}</Text><Text>⌄</Text></Pressable>{targets.isFetching?<Text>Loading clients…</Text>:null}{targets.isError?<Button label="Retry clients" onPress={()=>void targets.refetch()}/>:null}{clientsOpen?targets.data?.map(client=><Check key={client.id} label={client.label} checked={clients.includes(client.id)} onPress={()=>setClients(old=>old.includes(client.id)?old.filter(id=>id!==client.id):[...old,client.id])}/>):null}</View><Field label="Title" placeholder="Enter announcement title" value={title} onChangeText={setTitle} maxLength={160}/><Field label="Body" placeholder="Enter announcement body" value={body} onChangeText={setBody} multiline numberOfLines={4} style={{minHeight:100,padding:12,flex:1}}/>
 <Field label="From Date" placeholder="YYYY-MM-DD" value={from} onChangeText={setFrom}/><Field label="From Time" placeholder="HH:mm" value={fromTime} onChangeText={setFromTime}/><Field label="To Date" placeholder="YYYY-MM-DD" value={to} onChangeText={setTo}/><Field label="To Time" placeholder="HH:mm" value={toTime} onChangeText={setToTime}/><Check label="Active" checked={active} onPress={()=>setActive(!active)}/><Check label="Don't Show Again" checked={dontShowAgain} onPress={()=>setDontShowAgain(!dontShowAgain)}/>{error?<Text accessibilityRole="alert" style={form.error}>{error}</Text>:null}<Button label={busy?'Saving…':existing?'Save':'Create'} disabled={busy} onPress={()=>void save()}/></Screen>;
}
